sudo apt update && sudo apt install -y \
 0trace
7zip
aapt
above
accountsservice
acl
adb
adduser
adwaita-icon-theme
aesfix
aeskeyfind
afflib-tools
afl++
afl++-doc
aidl
aircrack-ng
airgeddon
alsa-topology-conf
alsa-ucm-conf
altdns
amap
amass
amass-common
amd64-microcode
androguard
android-framework-res
android-libaapt:amd64
android-libandroidfw:amd64
android-libbacktrace:amd64
android-libbase:amd64
android-libboringssl:amd64
android-libcutils:amd64
android-liblog:amd64
android-libsparse:amd64
android-libutils:amd64
android-libziparchive:amd64
android-sdk
android-sdk-build-tools
android-sdk-build-tools-common
android-sdk-common
android-sdk-libsparse-utils
android-sdk-platform-tools
android-sdk-platform-tools-common
android-udev-rules
ant
ant-optional
antlr
apache-users
apache2
apache2-bin
apache2-data
apache2-utils
apksigner
apktool
apparmor
apple-bleee
apt
apt-file
apt-utils
arj
arjun
arkime
armitage
arp-scan
arping
arpwatch
asleap
aspell
aspell-en
aspnetcore-runtime-6.0
aspnetcore-targeting-pack-6.0
assetfinder
at-spi2-common
at-spi2-core
atftpd
atril
atril-common
attr
autopsy
autorecon
avahi-daemon
avahi-utils
awscli
axel
azurehound
b374k
base-files
base-passwd
base58
bash
bash-completion
bed
beef-xss
berate-ap
bettercap
bettercap-caplets
bettercap-ui
bind9-dnsutils
bind9-host
bind9-libs:amd64
binfmt-support
bing-ip2hosts
binutils
binutils-common:amd64
binutils-mingw-w64
binutils-mingw-w64-i686
binutils-mingw-w64-ucrt64
binutils-mingw-w64-x86-64
binutils-x86-64-linux-gnu
binwalk
binwalk3
black
bladerf
bloodhound
bloodhound-ce-python
bloodhound.py
bloodyad
blt
blue-hydra
bluelog
blueman
blueranger
bluesnarfer
bluez
bluez-firmware
bluez-hcidump
bluez-obexd
bluez-test-scripts
bnd
bopscrk
bpftool
braa
bruteforce-luks
bruteforce-salted-openssl
bruteforce-wallet
bruteshark
brutespray
bsd-mailx
bsdextrautils
bsdutils
btscanner
bubblewrap
build-essential
bulk-extractor
bully
bundler
burpsuite
busybox
bytecode-viewer
bzip2
ca-certificates
ca-certificates-java
ca-certificates-mono
cabextract
cadaver
caldera
calicoctl
capstone-tool
cassandra
cassandra-libs
castxml
catfish
ccrypt
ccze
celery
certgraph
certi
certipy-ad
cewl
cgpt
chainsaw
changeme
chaosreader
cherrytree
chirp
chisel
chisel-common-binaries
chkrootkit
chntpw
chromium
chromium-common
chromium-driver
chromium-sandbox
cifs-utils
cilium-cli
cisco-auditing-tool
cisco-global-exploiter
cisco-ocs
cisco-torch
cisco7crack
clamav
clamav-base
clamav-freshclam
clang
clang-18
clang-19
clang-tools-19
cli-common
cloud-enum
cloudbrute
cmospwd
cmseek
cntlm
code-oss
coercer
colly
colord
colord-data
comerr-dev:amd64
command-not-found
commix
console-setup
console-setup-linux
containerd
copy-router-config
coreboot-utils
coreutils
cosign
cowpatty
cpio
cpp
cpp-14
cpp-14-x86-64-linux-gnu
cpp-x86-64-linux-gnu
crack
crack-common
crackle
cracklib-runtime
crackmapexec
cramfsswap
creddump7
cri-tools
criu
crlfuzz
cron
cron-daemon-common
crowbar
crunch
cryptcat
cryptsetup
cryptsetup-bin
cryptsetup-initramfs
cryptsetup-nuke-password
cupid-hostapd
cupid-wpasupplicant
cups-pk-helper
curl
curlftpfs
cutecom
cutycapt
cyberchef
cymothoa
darkstat
dash
davtest
dbd
dbeaver
dbus
dbus-bin
dbus-daemon
dbus-session-bus-common
dbus-system-bus-common
dbus-user-session
dbus-x11
dc3dd
dcfldd
dconf-gsettings-backend:amd64
dconf-service
dcraw
ddrescue
de4dot
debconf
debconf-i18n
debian-archive-keyring
debianutils
debugedit
default-jdk
default-jdk-headless
default-jre
default-jre-headless
default-mysql-server
defectdojo
desktop-base
desktop-file-utils
dex2jar
dhcpcd-base
dhcpig
dictionaries-common
diffutils
dirb
dirbuster
dirmngr
dirsearch
dislocker
distro-info-data
dkms
dmeventd
dmidecode
dmitry
dmsetup
dmtracedump
dns-root-data
dns2tcp
dnscat2
dnscat2-client
dnscat2-server
dnschef
dnsenum
dnsgen
dnsmap
dnsmasq
dnsmasq-base
dnsrecon
dnstracer
dnstwist
dnswalk
dnsx
doc-base
docbook-xml
docker-buildx
docker-cli
docker.io
docutils-common
donut
doona
dos2unix
dosfstools
dotdotpwn
dotnet-apphost-pack-6.0
dotnet-host
dotnet-hostfxr-6.0
dotnet-runtime-6.0
dotnet-runtime-deps-6.0
dotnet-sdk-6.0
dotnet-targeting-pack-6.0
dpkg
dpkg-dev
dracut-install
dradis
driftnet
dscan
dsniff
dufflebag
dumpsterdiver
dumpzilla
dvisvgm
dwarf2json
e2fsprogs
eaphammer
eapmd5pass
easy-rsa
eatmydata
edb-debugger
edb-debugger-plugins:amd64
eject
eksctl
emacsen-common
email2phonenumber
emailharvester
enchant-2
engrampa
engrampa-common
entr
enum4linux
enum4linux-ng
enumiax
espeak
espeak-data:amd64
espeak-ng-data:amd64
etc1tool
ethtool
ettercap-common
ettercap-text-only
evil-ssdp
evil-winrm
evilginx2
evolution-data-server-common
ewf-tools
exe2hexbat
exfatprogs
exif
exiflooter
exifprobe
exim4-base
exim4-config
exim4-daemon-light
exiv2
exo-utils
expect
exploitdb
exploitdb-bin-sploits
exploitdb-papers
ext3grep
ext4magic
extundelete
eyewitness
f2fs-tools
fakeroot
faraday
faraday-agent-dispatcher
faraday-cli
fastboot
fastjar
fatcat
fcrackzip
fdisk
fern-wifi-cracker
feroxbuster
ferret-sidejack
ffmpeg
ffuf
fierce
figlet
fiked
file
finalrecon
findomain
findutils
finger
firebird4.0-common
firebird4.0-common-doc
firefox-esr
firewalk
firmware-amd-graphics
firmware-ath9k-htc
firmware-atheros
firmware-brcm80211
firmware-carl9170
firmware-intel-graphics
firmware-intel-misc
firmware-intel-sound
firmware-iwlwifi
firmware-libertas
firmware-linux
firmware-linux-free
firmware-linux-nonfree
firmware-marvell-prestera
firmware-mediatek
firmware-misc-nonfree
firmware-mod-kit
firmware-nvidia-graphics
firmware-realtek
firmware-sof-signed
firmware-ti-connectivity
firmware-zd1211
flac
flameshot
flashrom
flatpak
flex
fontconfig
fontconfig-config
fonts-cantarell
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-dejavu-mono
fonts-droid-fallback
fonts-firacode
fonts-font-awesome
fonts-freefont-ttf
fonts-glyphicons-halflings
fonts-hack
fonts-lato
fonts-liberation
fonts-liberation-sans-narrow
fonts-lmodern
fonts-lyx
fonts-mathjax
fonts-noto-color-emoji
fonts-noto-mono
fonts-octicons
fonts-quicksand
fonts-texgyre
fonts-texgyre-math
fonts-urw-base35
fonts-wine
foremost
forensic-artifacts
forensics-colorize
fping
fragrouter
framework2
freeradius
freeradius-common
freeradius-config
freeradius-utils
freeradius-wpe
freerdp3-x11
freetds-common
ftester
ftp
fuse3
fwbuilder
fwbuilder-common
fwbuilder-doc
g++
g++-14
g++-14-x86-64-linux-gnu
g++-mingw-w64
g++-mingw-w64-i686
g++-mingw-w64-i686-posix
g++-mingw-w64-i686-win32
g++-mingw-w64-x86-64
g++-mingw-w64-x86-64-posix
g++-mingw-w64-x86-64-win32
g++-x86-64-linux-gnu
galera-4
galleta
gawk
gcc
gcc-14
gcc-14-base:amd64
gcc-14-x86-64-linux-gnu
gcc-mingw-w64
gcc-mingw-w64-base:amd64
gcc-mingw-w64-i686
gcc-mingw-w64-i686-posix
gcc-mingw-w64-i686-posix-runtime
gcc-mingw-w64-i686-win32
gcc-mingw-w64-i686-win32-runtime
gcc-mingw-w64-x86-64
gcc-mingw-w64-x86-64-posix
gcc-mingw-w64-x86-64-posix-runtime
gcc-mingw-w64-x86-64-win32
gcc-mingw-w64-x86-64-win32-runtime
gcc-x86-64-linux-gnu
gcr
gcr4
gdal-data
gdal-plugins:amd64
gdb
gdb-peda
gdisk
geoclue-2.0
geoip-database
geoipupdate
getallurls
getsploit
gettext-base
ghidra
ghidra-data
ghostscript
ghostwriter
gir1.2-atk-1.0:amd64
gir1.2-atspi-2.0:amd64
gir1.2-ayatanaappindicator3-0.1
gir1.2-freedesktop:amd64
gir1.2-gdkpixbuf-2.0:amd64
gir1.2-girepository-2.0:amd64
gir1.2-glib-2.0:amd64
gir1.2-gstreamer-1.0:amd64
gir1.2-gtk-3.0:amd64
gir1.2-gtkspell3-3.0:amd64
gir1.2-handy-1:amd64
gir1.2-harfbuzz-0.0:amd64
gir1.2-keybinder-3.0
gir1.2-libxfce4ui-2.0:amd64
gir1.2-libxfce4util-1.0:amd64
gir1.2-nm-1.0:amd64
gir1.2-notify-0.7:amd64
gir1.2-packagekitglib-1.0
gir1.2-pango-1.0:amd64
gir1.2-polkit-1.0
gir1.2-secret-1:amd64
gir1.2-vte-2.91:amd64
gir1.2-wnck-3.0:amd64
gir1.2-xfconf-0:amd64
git
git-man
gitleaks
gitxray
glib-networking:amd64
glib-networking-common
glib-networking-services
gnome-accessibility-themes
gnome-disk-utility
gnome-icon-theme
gnome-keyring
gnome-keyring-pkcs11:amd64
gnome-system-tools
gnome-terminal
gnome-terminal-data
gnome-themes-extra:amd64
gnome-themes-extra-data
gnupg
gnupg-l10n
gnupg-utils
gnuradio
gnuradio-dev
gnustep-base-common
gnustep-base-runtime
gnustep-common
gnustep-multiarch:amd64
gnutls-bin
go-l2tp
gobuster
godoh
golang-1.24-go
golang-1.24-src
golang-any:amd64
golang-github-aws-aws-sdk-go-dev
golang-github-binject-go-donut
golang-github-davecgh-go-spew-dev
golang-github-deckarep-golang-set-dev
golang-github-jmespath-go-jmespath-dev
golang-github-klauspost-cpuid-dev
golang-github-pmezard-go-difflib-dev
golang-github-stretchr-objx-dev
golang-go:amd64
golang-golang-x-crypto-dev
golang-golang-x-net-dev
golang-golang-x-sys-dev
golang-golang-x-term-dev
golang-golang-x-text-dev
golang-gopkg-yaml.v2-dev
golang-lukechampine-blake3-dev
golang-src
goldeneye
goofile
google-nexus-tools
gophish
goshs
gospider
gowitness
gpart
gparted
gparted-common
gpg
gpg-agent
gpg-wks-client
gpgconf
gpgsm
gpgv
gpp-decrypt
gpsd
gpsd-clients
gpsd-tools
gqrx-sdr
gr-air-modes
gr-fosphor
gr-funcube
gr-iqbal
gr-osmosdr
gradle
graphviz
graudit
greenbone-feed-sync
greenbone-security-assistant
grep
grim
groff-base
grokevt
groovy
grub-common
grub-pc
grub-pc-bin
grub2-common
gsad
gsettings-desktop-schemas
gsocket
gss-ntlmssp
gstreamer1.0-gl:amd64
gstreamer1.0-libav:amd64
gstreamer1.0-plugins-bad:amd64
gstreamer1.0-plugins-base:amd64
gstreamer1.0-plugins-good:amd64
gstreamer1.0-plugins-ugly:amd64
gstreamer1.0-x:amd64
gtk-update-icon-cache
gtk2-engines-pixbuf:amd64
gtkhash
guymager
gvfs:amd64
gvfs-backends
gvfs-common
gvfs-daemons
gvfs-fuse
gvfs-libs:amd64
gvm
gvm-tools
gvmd
gvmd-common
gzip
h8mail
hackrf
hak5-wifi-coconut
hakrawler
hamster-sidejack
hash-identifier
hashcat
hashcat-data
hashcat-utils
hashdeep
hashid
hashrat
haveged
havoc
hb-honeypot
hcxdumptool
hcxtools
hdparm
heartleech
hekatomb
hexinject
hexwalk
hicolor-icon-theme
hoaxshell
horst
hostapd
hostapd-mana
hostapd-wpe
hosthunter
hostname
hostsman
hotpatch
hping3
hprof-conv
htshells
httprint
httprobe
httpx-toolkit
httrack
hubble
humble
hunspell-en-us
hurl
hwloc
hydra
hyperion
hyphen-en-us
i2c-tools
i965-va-driver:amd64
iaxflood
ibombshell
ibverbs-providers:amd64
icu-devtools
ident-user-enum
ieee-data
ifenslave
ifupdown
iio-sensor-proxy
ike-scan
imagemagick
imagemagick-7-common
imagemagick-7.q16
imhex
imhex-patterns
impacket-scripts
inetsim
inetutils-telnet
init
init-system-helpers
initramfs-tools
initramfs-tools-bin
initramfs-tools-core
inspectrum
inspy
instaloader
intel-media-va-driver:amd64
intel-microcode
intrace
inviteflood
iodine
ipp-usb
iproute2
iptables
iputils-ping
ipv6toolkit
ipxe-qemu
ipython3
irpas
isa-support:amd64
isc-dhcp-common
isc-dhcp-server
ismtp
iso-codes
isort
isr-evilgrade
isympy-common
isympy3
iucode-tool
ivre
ivy
iw
jadx
jarwrapper
java-common
java-wrappers
javascript-common
javasnoop
jboss-autopwn
jd-gui
john
john-data
johnny
joomscan
joplin
jq
jsp-file-browser
jsql-injection
junit
junit4
kali-archive-keyring
kali-autopilot
kali-community-wallpapers
kali-defaults
kali-defaults-desktop
kali-desktop-base
kali-desktop-core
kali-desktop-xfce
kali-grant-root
kali-hidpi-mode
kali-linux-core
kali-linux-default
kali-linux-everything
kali-linux-firmware
kali-linux-headless
kali-linux-large
kali-linux-wsl
kali-menu
kali-system-cli
kali-system-core
kali-system-gui
kali-themes
kali-themes-common
kali-tools-802-11
kali-tools-bluetooth
kali-tools-crypto-stego
kali-tools-database
kali-tools-detect
kali-tools-exploitation
kali-tools-forensics
kali-tools-fuzzing
kali-tools-gpu
kali-tools-hardware
kali-tools-identify
kali-tools-information-gathering
kali-tools-passwords
kali-tools-post-exploitation
kali-tools-protect
kali-tools-recover
kali-tools-reporting
kali-tools-respond
kali-tools-reverse-engineering
kali-tools-rfid
kali-tools-sdr
kali-tools-sniffing-spoofing
kali-tools-social-engineering
kali-tools-top10
kali-tools-voip
kali-tools-vulnerability
kali-tools-web
kali-tools-windows-resources
kali-tools-wireless
kali-tweaks
kali-undercover
kali-wallpapers-2019.4
kali-wallpapers-2020.4
kali-wallpapers-2022
kali-wallpapers-2023
kali-wallpapers-2024
kali-wallpapers-2025
kali-wallpapers-all
kali-wallpapers-legacy
kalibrate-rtl
kbd
kerberoast
keyboard-configuration
keyutils
kismet
kismet-capture-common
kismet-capture-hak5-wifi-coconut
kismet-capture-linux-bluetooth
kismet-capture-linux-wifi
kismet-capture-nrf-51822
kismet-capture-nrf-52840
kismet-capture-nrf-mousejack
kismet-capture-nxp-kw41z
kismet-capture-rz-killerbee
kismet-capture-ti-cc-2531
kismet-capture-ti-cc-2540
kismet-capture-ubertooth-one
kismet-core
kismet-logtools
klibc-utils
kmod
knocker
koadic
krb5-config
krb5-locales
krb5-multidev:amd64
kubernetes-helm
kustomize
lame
lapsdumper
laptop-detect
laudanum
layer-shell-qt
lbd
ldap-utils
ldeep
legion
less
lib32gcc-s1
lib32stdc++6
liba52-0.7.4:amd64
libaa1:amd64
libaacs0:amd64
libabsl20240722:amd64
libaccountsservice0:amd64
libacl1:amd64
libad9361-0:amd64
libadns1t64
libaec0:amd64
libafflib0t64:amd64
libaio1t64:amd64
libairspy0:amd64
libairspyhf1:amd64
libalgorithm-c3-perl
libalgorithm-diff-perl
libalgorithm-diff-xs-perl
libalgorithm-merge-perl
libann0
libantlr-java
libantlr3-runtime-java
libao-common
libao4:amd64
libaom3:amd64
libaopalliance-java
libapache-pom-java
libapache2-mod-php
libapache2-mod-php8.4
libapksig-java
libapparmor1:amd64
libappstream5:amd64
libapr1t64:amd64
libaprutil1-dbd-sqlite3:amd64
libaprutil1-ldap:amd64
libaprutil1t64:amd64
libapt-pkg-perl
libapt-pkg7.0:amd64
libarchive-zip-perl
libarchive13t64:amd64
libargon2-1:amd64
libarmadillo14
libarpack2t64:amd64
libasan8:amd64
libasm-java
libasound2-data
libasound2-plugins:amd64
libasound2t64:amd64
libaspell15:amd64
libass9:amd64
libassuan9:amd64
libasyncns0:amd64
libatasmart4:amd64
libatinject-jsr330-api-java
libatk-bridge2.0-0t64:amd64
libatk-wrapper-java
libatk-wrapper-java-jni:amd64
libatk1.0-0t64:amd64
libatkmm-1.6-1v5:amd64
libatomic1:amd64
libatrildocument3t64
libatrilview3t64
libatspi2.0-0t64:amd64
libattr1:amd64
libaudio2:amd64
libaudit-common
libaudit1:amd64
libauthen-sasl-perl
libavahi-client3:amd64
libavahi-common-data:amd64
libavahi-common3:amd64
libavahi-core7:amd64
libavahi-glib1:amd64
libavc1394-0:amd64
libavcodec61:amd64
libavdevice61:amd64
libavfilter10:amd64
libavformat61:amd64
libavif16:amd64
libavtp0:amd64
libavutil59:amd64
libayatana-appindicator3-1
libayatana-ido3-0.4-0:amd64
libayatana-indicator3-7:amd64
libb-hooks-endofscope-perl
libb-hooks-op-check-perl:amd64
libb2-1:amd64
libbabeltrace1:amd64
libbcel-java
libbcg729-0:amd64
libbcpg-java
libbcprov-java
libbde1t64:amd64
libbdplus0:amd64
libbfio1:amd64
libbindex-java
libbinutils:amd64
libbit-vector-perl:amd64
libbladerf2:amd64
libblas3:amd64
libblkid1:amd64
libblkio1:amd64
libblockdev-crypto3:amd64
libblockdev-fs3:amd64
libblockdev-loop3:amd64
libblockdev-mdraid3:amd64
libblockdev-nvme3:amd64
libblockdev-part3:amd64
libblockdev-swap3:amd64
libblockdev-utils3:amd64
libblockdev3:amd64
libblosc1:amd64
libblosc2-4:amd64
libbluetooth-dev:amd64
libbluetooth3:amd64
libbluray2:amd64
libboost-atomic1.83-dev:amd64
libboost-atomic1.83.0:amd64
libboost-chrono1.83-dev:amd64
libboost-chrono1.83.0t64:amd64
libboost-date-time1.83-dev:amd64
libboost-date-time1.83.0:amd64
libboost-filesystem1.83-dev:amd64
libboost-filesystem1.83.0:amd64
libboost-iostreams1.83.0:amd64
libboost-program-options1.83-dev:amd64
libboost-program-options1.83.0:amd64
libboost-python1.83.0
libboost-regex1.83-dev:amd64
libboost-regex1.83.0:amd64
libboost-serialization1.83-dev:amd64
libboost-serialization1.83.0:amd64
libboost-system1.83-dev:amd64
libboost-system1.83.0:amd64
libboost-test1.83-dev:amd64
libboost-test1.83.0:amd64
libboost-thread1.83-dev:amd64
libboost-thread1.83.0:amd64
libboost1.83-dev:amd64
libbpf1:amd64
libbrlapi0.8:amd64
libbrotli1:amd64
libbs2b0:amd64
libbsd0:amd64
libbsf-java
libbsh-java
libbson-1.0-0t64
libbtbb1:amd64
libbytes-random-secure-perl
libbytesize-common
libbytesize1:amd64
libbz2-1.0:amd64
libc-bin
libc-dev-bin
libc-l10n
libc6:amd64
libc6-dev:amd64
libc6-i386
libcaca0:amd64
libcacard0:amd64
libcaes1:amd64
libcairo-gobject2:amd64
libcairo-script-interpreter2:amd64
libcairo2:amd64
libcairomm-1.0-1v5:amd64
libcairomm-1.16-1:amd64
libcaja-extension1:amd64
libcamel-1.2-64t64:amd64
libcanberra-gtk3-0:amd64
libcanberra-gtk3-module:amd64
libcanberra0:amd64
libcap-dev:amd64
libcap-ng0:amd64
libcap2:amd64
libcap2-bin
libcapi20-3t64:amd64
libcapstone-dev:amd64
libcapstone5:amd64
libcares2:amd64
libcarp-clan-perl
libcbor0.10:amd64
libcc1-0:amd64
libccid
libcdi-api-java
libcdio-cdda2t64:amd64
libcdio-paranoia2t64:amd64
libcdio19t64:amd64
libcdparanoia0:amd64
libcdt5:amd64
libcfitsio10t64:amd64
libcgi-fast-perl
libcgi-pm-perl
libcgraph6:amd64
libcharon-extauth-plugins
libchromaprint1:amd64
libcjson1:amd64
libclamav12:amd64
libclang-common-18-dev:amd64
libclang-common-19-dev:amd64
libclang-cpp18
libclang-cpp19
libclang-rt-18-dev:amd64
libclang-rt-19-dev:amd64
libclang1-18
libclang1-19
libclass-c3-perl
libclass-c3-xs-perl
libclass-data-inheritable-perl
libclass-inspector-perl
libclass-load-perl
libclass-load-xs-perl
libclass-method-modifiers-perl
libclass-singleton-perl
libclass-tiny-perl
libclass-xsaccessor-perl
libcli1.10t64:amd64
libclone-perl:amd64
libcloudproviders0:amd64
libcmark-gfm-extensions0.29.0.gfm.13:amd64
libcmark-gfm0.29.0.gfm.13:amd64
libcodec2-1.2:amd64
libcolord2:amd64
libcolorhug2:amd64
libcom-err2:amd64
libcommon-sense-perl:amd64
libcommons-cli-java
libcommons-codec-java
libcommons-collections3-java
libcommons-compress-java
libcommons-io-java
libcommons-lang-java
libcommons-lang3-java
libcommons-logging-java
libcommons-parent-java
libcommons-text-java
libcompel1:amd64
libcompress-raw-lzma-perl:amd64
libconfig++11:amd64
libconfig-inifiles-perl
libconfig11:amd64
libcppunit-1.15-0:amd64
libcppunit-dev:amd64
libcpuinfo0:amd64
libcrack2:amd64
libcreg1t64:amd64
libcrypt-dev:amd64
libcrypt-random-seed-perl
libcrypt-rc4-perl
libcrypt-ssleay-perl
libcrypt1:amd64
libcrypto++8t64:amd64
libcryptsetup12:amd64
libct4:amd64
libctf-nobfd0:amd64
libctf0:amd64
libcups2t64:amd64
libcurl3t64-gnutls:amd64
libcurl4t64:amd64
libdaemon0:amd64
libdaq2
libdaq3
libdata-dump-perl
libdata-optlist-perl
libdate-calc-perl
libdate-calc-xs-perl:amd64
libdate-manip-perl
libdatetime-format-builder-perl
libdatetime-format-iso8601-perl
libdatetime-format-strptime-perl
libdatetime-locale-perl
libdatetime-perl
libdatetime-timezone-perl
libdatrie1:amd64
libdav1d7:amd64
libdaxctl1:amd64
libdb5.3t64:amd64
libdbd-mariadb-perl
libdbd-sqlite3-perl:amd64
libdbi-perl:amd64
libdbus-1-3:amd64
libdbus-1-dev:amd64
libdbus-glib-1-2:amd64
libdbusmenu-glib4:amd64
libdbusmenu-gtk3-4:amd64
libdc1394-25:amd64
libdca0:amd64
libdconf1:amd64
libdd-plist-java
libde265-0:amd64
libdebconfclient0:amd64
libdebuginfod-common
libdebuginfod1t64:amd64
libdecor-0-0:amd64
libdeflate0:amd64
libdevel-callchecker-perl:amd64
libdevel-caller-perl:amd64
libdevel-globaldestruction-perl
libdevel-lexalias-perl
libdevel-overloadinfo-perl
libdevel-partialdump-perl
libdevel-stacktrace-perl
libdevmapper-event1.02.1:amd64
libdevmapper1.02.1:amd64
libdigest-bubblebabble-perl
libdigest-crc-perl
libdigest-hmac-perl
libdigest-md4-perl
libdigest-md5-file-perl
libdigest-perl-md5-perl
libdislocker0.7t64
libdisplay-info2:amd64
libdist-checkconflicts-perl
libdistorm3-3:amd64
libdjvulibre-text
libdjvulibre21:amd64
libdlt2:amd64
libdnlib2.1-cil
libdnnl3.6:amd64
libdom4j-java
libdotconf0:amd64
libdouble-conversion3:amd64
libdpkg-perl
libdrm-amdgpu1:amd64
libdrm-common
libdrm-intel1:amd64
libdrm-nouveau2:amd64
libdrm-radeon1:amd64
libdrm2:amd64
libduktape207:amd64
libdumbnet1:amd64
libdv4t64:amd64
libdvdnav4:amd64
libdvdread8t64:amd64
libdw1t64:amd64
libdynaloader-functions-perl
libeac3:amd64
libeatmydata1:amd64
libebackend-1.2-11t64:amd64
libebook-1.2-21t64:amd64
libebook-contacts-1.2-4t64:amd64
libebur128-1:amd64
libeclipse-jdt-annotation-java
libedata-book-1.2-27t64:amd64
libedataserver-1.2-27t64:amd64
libedit2:amd64
libefiboot1t64:amd64
libefivar1t64:amd64
libegl-mesa0:amd64
libegl1:amd64
libeigen3-dev
libel-api-java
libelf1t64:amd64
libenchant-2-2:amd64
libencode-locale-perl
libepoxy0:amd64
liberror-perl
liberror-prone-java
libesedb1t64:amd64
libespeak-ng1:amd64
libespeak1:amd64
libestr0:amd64
libev4t64:amd64
libeval-closure-perl
libevdev2:amd64
libevent-2.1-7t64:amd64
libevent-core-2.1-7t64:amd64
libevent-openssl-2.1-7t64:amd64
libevent-pthreads-2.1-7t64:amd64
libevt1t64:amd64
libevtx1t64:amd64
libewf2:amd64
libexception-class-perl
libexecs1:amd64
libexif12:amd64
libexiv2-28:amd64
libexiv2-data
libexo-2-0:amd64
libexo-common
libexpat1:amd64
libexpat1-dev:amd64
libext2fs2t64:amd64
libfaad2:amd64
libfakeroot:amd64
libfastjson4:amd64
libfbclient2:amd64
libfcgi-bin
libfcgi-perl
libfcgi0t64:amd64
libfcrypto1:amd64
libfdisk1:amd64
libfdt1:amd64
libfec0:amd64
libfelix-framework-java
libfelix-gogo-runtime-java
libfelix-osgi-obr-java
libfelix-resolver-java
libffado2:amd64
libffi-dev:amd64
libffi8:amd64
libfftw3-bin
libfftw3-dev:amd64
libfftw3-double3:amd64
libfftw3-long3:amd64
libfftw3-quad3:amd64
libfftw3-single3:amd64
libfido2-1:amd64
libfile-basedir-perl
libfile-desktopentry-perl
libfile-fcntllock-perl
libfile-listing-perl
libfile-mimeinfo-perl
libfile-sharedir-perl
libfindbugs-java
libfindrtp
libfl-dev:amd64
libfl2:amd64
libflac14:amd64
libflashrom1:amd64
libflite1:amd64
libfluidsynth3:amd64
libfmt-dev:amd64
libfmt10:amd64
libfont-afm-perl
libfontbox-java
libfontconfig1:amd64
libfontenc1:amd64
libfox-1.6-0:amd64
libfreeaptx0:amd64
libfreefare-bin
libfreefare0t64:amd64
libfreeradius3
libfreerdp-client3-3:amd64
libfreerdp3-3:amd64
libfreesrp0:amd64
libfreetype6:amd64
libfreexl1:amd64
libfribidi0:amd64
libfsapfs1t64:amd64
libfsext1t64:amd64
libfsfat1:amd64
libfshfs1t64:amd64
libfsntfs1t64:amd64
libfstrm0:amd64
libfsverity0:amd64
libfsxfs1t64:amd64
libftdi1-2:amd64
libfuse2t64:amd64
libfuse3-4:amd64
libfuzzy2:amd64
libfvde1t64:amd64
libfwnt1t64:amd64
libfwsi1t64:amd64
libfxscintilla20
libfyba0t64:amd64
libgarcon-1-0:amd64
libgarcon-common
libgarcon-gtk3-1-0:amd64
libgav1-1:amd64
libgbm1:amd64
libgc1:amd64
libgcab-1.0-0:amd64
libgcc-14-dev:amd64
libgcc-s1:amd64
libgck-1-0:amd64
libgck-2-2:amd64
libgcr-4-4:amd64
libgcr-base-3-1:amd64
libgcr-ui-3-1:amd64
libgcrypt20:amd64
libgd3:amd64
libgdal36:amd64
libgdata-common
libgdata22:amd64
libgdbm-compat4t64:amd64
libgdbm6t64:amd64
libgdiplus
libgdk-pixbuf-2.0-0:amd64
libgdk-pixbuf2.0-bin
libgdk-pixbuf2.0-common
libgeoip1t64:amd64
libgeos-c1t64:amd64
libgeos3.13.1:amd64
libgeotiff5:amd64
libgeronimo-annotation-1.3-spec-java
libgeronimo-interceptor-3.0-spec-java
libgfapi0:amd64
libgfortran5:amd64
libgfrpc0:amd64
libgfxdr0:amd64
libgif7:amd64
libgirepository-1.0-1:amd64
libgit2-1.9:amd64
libgl-dev:amd64
libgl1:amd64
libgl1-mesa-dri:amd64
libgles2:amd64
libglfw3:amd64
libglib2.0-0t64:amd64
libglib2.0-bin
libglib2.0-data
libglibmm-2.4-1t64:amd64
libglibmm-2.68-1t64:amd64
libglu1-mesa:amd64
libglu1-mesa-dev:amd64
libglusterfs0:amd64
libglut-dev:amd64
libglut3.12:amd64
libglvnd0:amd64
libglx-dev:amd64
libglx-mesa0:amd64
libglx0:amd64
libgme0:amd64
libgmp-dev:amd64
libgmp10:amd64
libgmpxx4ldbl:amd64
libgnuradio-air-modes1t64
libgnuradio-analog3.10.12:amd64
libgnuradio-audio3.10.12:amd64
libgnuradio-blocks3.10.12:amd64
libgnuradio-channels3.10.12:amd64
libgnuradio-digital3.10.12:amd64
libgnuradio-dtv3.10.12:amd64
libgnuradio-fec3.10.12:amd64
libgnuradio-fft3.10.12:amd64
libgnuradio-filter3.10.12:amd64
libgnuradio-fosphor3.9.0:amd64
libgnuradio-funcube3.10.0
libgnuradio-iio3.10.12:amd64
libgnuradio-iqbalance3.9.0
libgnuradio-network3.10.12:amd64
libgnuradio-osmosdr0.2.0t64:amd64
libgnuradio-pdu3.10.12:amd64
libgnuradio-pmt3.10.12:amd64
libgnuradio-qtgui3.10.12:amd64
libgnuradio-runtime3.10.12:amd64
libgnuradio-soapy3.10.12:amd64
libgnuradio-trellis3.10.12:amd64
libgnuradio-uhd3.10.12:amd64
libgnuradio-video-sdl3.10.12:amd64
libgnuradio-vocoder3.10.12:amd64
libgnuradio-wavelet3.10.12:amd64
libgnuradio-zeromq3.10.12:amd64
libgnustep-base1.31:amd64
libgnutls-dane0t64:amd64
libgnutls-openssl27t64:amd64
libgnutls30t64:amd64
libgoa-1.0-0b:amd64
libgoa-1.0-common
libgomp1:amd64
libgoogle-gson-java
libgpars-groovy-java
libgpg-error-l10n
libgpg-error0:amd64
libgpgme11t64:amd64
libgpgmepp6t64:amd64
libgphoto2-6t64:amd64
libgphoto2-l10n
libgphoto2-port12t64:amd64
libgpm2:amd64
libgprofng0:amd64
libgps30t64:amd64
libgradle-core-java
libgradle-plugins-java
libgraphene-1.0-0:amd64
libgraphite2-3:amd64
libgs-common
libgs10:amd64
libgs10-common
libgsf-1-114:amd64
libgsf-1-common
libgsl28:amd64
libgslcblas0:amd64
libgsm1:amd64
libgsm1-dev:amd64
libgspell-1-3:amd64
libgspell-1-common
libgssapi-krb5-2:amd64
libgssdp-1.6-0:amd64
libgssrpc4t64:amd64
libgstreamer-gl1.0-0:amd64
libgstreamer-plugins-bad1.0-0:amd64
libgstreamer-plugins-base1.0-0:amd64
libgstreamer1.0-0:amd64
libgtk-3-0t64:amd64
libgtk-3-bin
libgtk-3-common
libgtk-4-1:amd64
libgtk-4-bin
libgtk-4-common
libgtk-4-media-gstreamer
libgtk-layer-shell0
libgtkmm-3.0-1t64:amd64
libgtkmm-4.0-0:amd64
libgtksourceview-4-0:amd64
libgtksourceview-4-common
libgtkspell3-3-0:amd64
libgtop-2.0-11:amd64
libgtop2-common
libgts-0.7-5t64:amd64
libgts-bin
libguava-java
libgudev-1.0-0:amd64
libguice-java
libgumbo3:amd64
libgupnp-1.6-0:amd64
libgupnp-igd-1.6-0:amd64
libgusb2:amd64
libguytools2t64
libgvc6
libgvm22t64:amd64
libgvpr2:amd64
libgxps2t64:amd64
libhackrf0:amd64
libhamcrest-java
libhamlib4t64:amd64
libhandy-1-0:amd64
libharfbuzz-gobject0:amd64
libharfbuzz-icu0:amd64
libharfbuzz-subset0:amd64
libharfbuzz0b:amd64
libhashkit2t64:amd64
libhavege2:amd64
libhawtjni-runtime-java
libhdf4-0-alt:amd64
libhdf5-310:amd64
libhdf5-hl-310:amd64
libheif-plugin-aomenc:amd64
libheif-plugin-dav1d:amd64
libheif-plugin-libde265:amd64
libheif-plugin-x265:amd64
libheif1:amd64
libhfstospell11:amd64
libhidapi-hidraw0:amd64
libhidapi-libusb0:amd64
libhiredis1.1.0:amd64
libhivex-bin
libhivex0:amd64
libhogweed6t64:amd64
libhtml-form-perl
libhtml-format-perl
libhtml-linkextractor-perl
libhtml-parser-perl:amd64
libhtml-tagset-perl
libhtml-template-perl
libhtml-tree-perl
libhtp2
libhttp-cookies-perl
libhttp-daemon-perl
libhttp-date-perl
libhttp-dav-perl
libhttp-message-perl
libhttp-negotiate-perl
libhttp-parser2.9:amd64
libhttpclient-java
libhttpcore-java
libhttrack2:amd64
libhunspell-1.7-0:amd64
libhwasan0:amd64
libhwloc-plugins:amd64
libhwloc15:amd64
libhwy1t64:amd64
libhyperscan5
libhyphen0:amd64
libi2c0:amd64
libibverbs1:amd64
libical3t64:amd64
libice-dev:amd64
libice6:amd64
libicu-dev:amd64
libicu72:amd64
libicu76:amd64
libidn12:amd64
libidn2-0:amd64
libiec61883-0:amd64
libieee1284-3t64:amd64
libigdgmm12:amd64
libiio0:amd64
libijs-0.35:amd64
libimage-exiftool-perl
libimagequant0:amd64
libimath-3-1-29t64:amd64
libimobiledevice-1.0-6:amd64
libimobiledevice-glue-1.0-0
libimport-into-perl
libinih1:amd64
libiniparser4:amd64
libinireader0:amd64
libinput-bin
libinput10:amd64
libinstpatch-1.0-2:amd64
libintl-perl
libintl-xs-perl
libio-all-lwp-perl
libio-all-perl
libio-compress-brotli-perl
libio-html-perl
libio-multiplex-perl
libio-socket-inet6-perl
libio-socket-socks-perl
libio-socket-ssl-perl
libio-stringy-perl
libip4tc2:amd64
libip6tc2:amd64
libipc-shareable-perl
libipc-system-simple-perl
libipt2
libiscsi7:amd64
libisl23:amd64
libitm1:amd64
libiw30t64:amd64
libjack-jackd2-0:amd64
libjansi-java
libjansi-native-java
libjansi1-java
libjansson4:amd64
libjarjar-java
libjatl-java
libjavaewah-java
libjavascriptcoregtk-4.1-0:amd64
libjaxen-java
libjaylink0:amd64
libjbig0:amd64
libjbig2dec0:amd64
libjcifs-java
libjcip-annotations-java
libjcode-pm-perl
libjcommander-java
libjcsp-java
libjemalloc2:amd64
libjetty9-java
libjformatstring-java
libjgit-java
libjim0.83:amd64
libjline2-java
libjna-java
libjna-jni
libjpeg-turbo-progs
libjpeg62-turbo:amd64
libjq1:amd64
libjs-bootstrap
libjs-bootstrap4
libjs-jquery
libjs-jquery-ui
libjs-mathjax
libjs-popper.js
libjs-prettify
libjs-sizzle
libjs-skeleton
libjs-sphinxdoc
libjs-underscore
libjsch-java
libjson-c5:amd64
libjson-glib-1.0-0:amd64
libjson-glib-1.0-common
libjson-perl
libjson-xs-perl
libjsoup-java
libjsp-api-java
libjsr166y-java
libjsr305-java
libjudydebian1
libjunixsocket-java
libjunixsocket-jni
libjxl0.11:amd64
libjxr-tools
libjxr0t64:amd64
libjzlib-java
libk5crypto3:amd64
libkadm5clnt-mit12:amd64
libkadm5srv-mit12:amd64
libkdb5-10t64:amd64
libkeybinder-3.0-0:amd64
libkeyutils1:amd64
libkf6archive-data
libkf6archive6:amd64
libkf6breezeicons6:amd64
libkf6codecs-data
libkf6codecs6:amd64
libkf6colorscheme-data
libkf6colorscheme6:amd64
libkf6config-bin
libkf6config-data
libkf6configcore6:amd64
libkf6configgui6:amd64
libkf6configwidgets-data
libkf6configwidgets6:amd64
libkf6coreaddons-data
libkf6coreaddons6:amd64
libkf6globalaccel-data
libkf6globalaccel6:amd64
libkf6guiaddons-bin
libkf6guiaddons-data
libkf6guiaddons6:amd64
libkf6i18n-data
libkf6i18n6:amd64
libkf6iconthemes-bin
libkf6iconthemes-data
libkf6iconthemes6:amd64
libkf6iconwidgets6:amd64
libkf6itemviews-data
libkf6itemviews6:amd64
libkf6sonnet-data
libkf6sonnetcore6:amd64
libkf6sonnetui6:amd64
libkf6syntaxhighlighting-data
libkf6syntaxhighlighting6:amd64
libkf6widgetsaddons-data
libkf6widgetsaddons6:amd64
libkf6xmlgui-data
libkf6xmlgui6:amd64
libklibc:amd64
libkmlbase1t64:amd64
libkmldom1t64:amd64
libkmlengine1t64:amd64
libkmod2:amd64
libkpathsea6:amd64
libkrb5-3:amd64
libkrb5-dev:amd64
libkrb5support0:amd64
libkryo-java
libksba8:amd64
libkxml2-java
liblab-gamut1:amd64
liblapack3:amd64
liblastlog2-2:amd64
liblayershellqtinterface6:amd64
liblc3-1:amd64
liblcms2-2:amd64
libldacbt-abr2:amd64
libldacbt-enc2:amd64
libldap-common
libldap2:amd64
libldb2:amd64
liblerc4:amd64
liblightcouch-java
liblightdm-gobject-1-0:amd64
liblilv-0-0:amd64
liblimesuite23.11-1:amd64
liblinear4:amd64
libliquid1:amd64
libllvm18:amd64
libllvm19:amd64
libllvmspirvlib18.1:amd64
liblmdb0:amd64
liblms7compact0:amd64
liblnk1t64:amd64
liblocale-gettext-perl
liblockfile-bin
liblockfile1:amd64
liblog4cpp5v5:amd64
liblog4j2-java
liblogback-java
liblognorm5:amd64
liblouis-data
liblouis20:amd64
liblqr-1-0:amd64
liblrdf0:amd64
liblsan0:amd64
liblsof0
libltc11:amd64
libltdl7:amd64
liblua5.1-0:amd64
liblua5.2-0:amd64
liblua5.3-0:amd64
liblua5.4-0:amd64
libluajit-5.1-2:amd64
libluajit-5.1-common
libluksde1t64:amd64
liblvm2cmd2.03:amd64
liblwp-mediatypes-perl
liblwp-protocol-https-perl
liblwp-protocol-socks-perl
liblz4-1:amd64
liblz4-dev:amd64
liblzf1:amd64
liblzma-dev:amd64
liblzma5:amd64
liblzo2-2:amd64
libmagic-dev:amd64
libmagic-mgc
libmagic1t64:amd64
libmagickcore-7.q16-10:amd64
libmagickcore-7.q16-10-extra:amd64
libmagickwand-7.q16-10:amd64
libmailtools-perl
libmalcontent-0-0:amd64
libmanette-0.2-0:amd64
libmariadb3:amd64
libmath-random-isaac-perl
libmath-random-isaac-xs-perl
libmaven-archiver-java
libmaven-file-management-java
libmaven-jar-plugin-java
libmaven-parent-java
libmaven-resolver-java
libmaven-shared-io-java
libmaven-shared-utils-java
libmaven3-core-java
libmaxminddb0:amd64
libmbedcrypto16:amd64
libmbedtls21:amd64
libmbedx509-7:amd64
libmbim-glib4:amd64
libmbim-proxy
libmbim-utils
libmcrypt4:amd64
libmd0:amd64
libmd4c0:amd64
libmdb3t64:amd64
libmdbsql3t64:amd64
libmemcached11t64:amd64
libmhash2:amd64
libmicrohttpd12t64:amd64
libmime-charset-perl
libminizip1t64:amd64
libminlog-java
libmirisdr4:amd64
libmjpegutils-2.1-0t64:amd64
libmm-glib0:amd64
libmnl0:amd64
libmodplug1:amd64
libmodule-find-perl
libmodule-implementation-perl
libmodule-runtime-conflicts-perl
libmodule-runtime-perl
libmongoc-1.0-0t64
libmongocrypt0:amd64
libmongodb-java
libmono-2.0-dev
libmono-accessibility4.0-cil
libmono-btls-interface4.0-cil
libmono-cairo4.0-cil
libmono-cecil-private-cil
libmono-cil-dev
libmono-codecontracts4.0-cil
libmono-compilerservices-symbolwriter4.0-cil
libmono-corlib4.5-cil
libmono-corlib4.5-dll
libmono-cscompmgd0.0-cil
libmono-csharp4.0c-cil
libmono-custommarshalers4.0-cil
libmono-data-tds4.0-cil
libmono-db2-1.0-cil
libmono-debugger-soft4.0a-cil
libmono-http4.0-cil
libmono-i18n-cjk4.0-cil
libmono-i18n-mideast4.0-cil
libmono-i18n-other4.0-cil
libmono-i18n-rare4.0-cil
libmono-i18n-west4.0-cil
libmono-i18n4.0-all
libmono-i18n4.0-cil
libmono-ldap4.0-cil
libmono-management4.0-cil
libmono-messaging-rabbitmq4.0-cil
libmono-messaging4.0-cil
libmono-microsoft-build-engine4.0-cil
libmono-microsoft-build-framework4.0-cil
libmono-microsoft-build-tasks-v4.0-4.0-cil
libmono-microsoft-build-utilities-v4.0-4.0-cil
libmono-microsoft-build4.0-cil
libmono-microsoft-csharp4.0-cil
libmono-microsoft-visualc10.0-cil
libmono-microsoft-web-infrastructure1.0-cil
libmono-oracle4.0-cil
libmono-parallel4.0-cil
libmono-peapi4.0a-cil
libmono-posix4.0-cil
libmono-rabbitmq4.0-cil
libmono-relaxng4.0-cil
libmono-security4.0-cil
libmono-sharpzip4.84-cil
libmono-simd4.0-cil
libmono-smdiagnostics0.0-cil
libmono-sqlite4.0-cil
libmono-system-componentmodel-composition4.0-cil
libmono-system-componentmodel-dataannotations4.0-cil
libmono-system-configuration-install4.0-cil
libmono-system-configuration4.0-cil
libmono-system-core4.0-cil
libmono-system-data-datasetextensions4.0-cil
libmono-system-data-entity4.0-cil
libmono-system-data-linq4.0-cil
libmono-system-data-services-client4.0-cil
libmono-system-data-services4.0-cil
libmono-system-data4.0-cil
libmono-system-deployment4.0-cil
libmono-system-design4.0-cil
libmono-system-drawing-design4.0-cil
libmono-system-drawing4.0-cil
libmono-system-dynamic4.0-cil
libmono-system-enterpriseservices4.0-cil
libmono-system-identitymodel-selectors4.0-cil
libmono-system-identitymodel4.0-cil
libmono-system-io-compression-filesystem4.0-cil
libmono-system-io-compression4.0-cil
libmono-system-json-microsoft4.0-cil
libmono-system-json4.0-cil
libmono-system-ldap-protocols4.0-cil
libmono-system-ldap4.0-cil
libmono-system-management4.0-cil
libmono-system-messaging4.0-cil
libmono-system-net-http-formatting4.0-cil
libmono-system-net-http-webrequest4.0-cil
libmono-system-net-http4.0-cil
libmono-system-net4.0-cil
libmono-system-numerics-vectors4.0-cil
libmono-system-numerics4.0-cil
libmono-system-reactive-core2.2-cil
libmono-system-reactive-debugger2.2-cil
libmono-system-reactive-experimental2.2-cil
libmono-system-reactive-interfaces2.2-cil
libmono-system-reactive-linq2.2-cil
libmono-system-reactive-observable-aliases0.0-cil
libmono-system-reactive-platformservices2.2-cil
libmono-system-reactive-providers2.2-cil
libmono-system-reactive-runtime-remoting2.2-cil
libmono-system-reactive-windows-forms2.2-cil
libmono-system-reactive-windows-threading2.2-cil
libmono-system-reflection-context4.0-cil
libmono-system-runtime-caching4.0-cil
libmono-system-runtime-durableinstancing4.0-cil
libmono-system-runtime-serialization-formatters-soap4.0-cil
libmono-system-runtime-serialization4.0-cil
libmono-system-runtime4.0-cil
libmono-system-security4.0-cil
libmono-system-servicemodel-activation4.0-cil
libmono-system-servicemodel-discovery4.0-cil
libmono-system-servicemodel-internals0.0-cil
libmono-system-servicemodel-routing4.0-cil
libmono-system-servicemodel-web4.0-cil
libmono-system-servicemodel4.0a-cil
libmono-system-serviceprocess4.0-cil
libmono-system-threading-tasks-dataflow4.0-cil
libmono-system-transactions4.0-cil
libmono-system-web-abstractions4.0-cil
libmono-system-web-applicationservices4.0-cil
libmono-system-web-dynamicdata4.0-cil
libmono-system-web-extensions-design4.0-cil
libmono-system-web-extensions4.0-cil
libmono-system-web-http-selfhost4.0-cil
libmono-system-web-http-webhost4.0-cil
libmono-system-web-http4.0-cil
libmono-system-web-mobile4.0-cil
libmono-system-web-mvc3.0-cil
libmono-system-web-razor2.0-cil
libmono-system-web-regularexpressions4.0-cil
libmono-system-web-routing4.0-cil
libmono-system-web-services4.0-cil
libmono-system-web-webpages-deployment2.0-cil
libmono-system-web-webpages-razor2.0-cil
libmono-system-web-webpages2.0-cil
libmono-system-web4.0-cil
libmono-system-windows-forms-datavisualization4.0a-cil
libmono-system-windows-forms4.0-cil
libmono-system-windows4.0-cil
libmono-system-workflow-activities4.0-cil
libmono-system-workflow-componentmodel4.0-cil
libmono-system-workflow-runtime4.0-cil
libmono-system-xaml4.0-cil
libmono-system-xml-linq4.0-cil
libmono-system-xml-serialization4.0-cil
libmono-system-xml4.0-cil
libmono-system4.0-cil
libmono-tasklets4.0-cil
libmono-webbrowser4.0-cil
libmono-webmatrix-data4.0-cil
libmono-windowsbase4.0-cil
libmono-xbuild-tasks4.0-cil
libmonosgen-2.0-1
libmonosgen-2.0-dev
libmoo-perl
libmoose-perl:amd64
libmosquitto1:amd64
libmotif-common
libmount1:amd64
libmousepad0:amd64
libmp3lame0:amd64
libmpc3:amd64
libmpcdec6:amd64
libmpeg2-4:amd64
libmpeg2encpp-2.1-0t64:amd64
libmpfi0:amd64
libmpfr6:amd64
libmpg123-0t64:amd64
libmplex2-2.1-0t64:amd64
libmro-compat-perl
libmsgraph-1-1:amd64
libmsi-1.0-0:amd64
libmsiecf1t64:amd64
libmspack0t64:amd64
libmtdev1t64:amd64
libmtp-common
libmtp-runtime
libmtp9t64:amd64
libmujs3:amd64
libmultiverse-core-java
libmupdf25.1
libmysofa1:amd64
libnamespace-autoclean-perl
libnamespace-clean-perl
libnative-platform-java
libnative-platform-jni
libnautilus-extension4:amd64
libncurses-dev:amd64
libncurses6:amd64
libncursesw6:amd64
libndctl6:amd64
libndp0:amd64
libndpi4.2t64:amd64
libnekohtml-java
libneon27t64:amd64
libneon27t64-gnutls:amd64
libnet-cidr-perl
libnet-dbus-perl
libnet-dns-perl
libnet-dns-sec-perl
libnet-http-perl
libnet-ident-perl
libnet-ip-perl
libnet-libidn2-perl
libnet-netmask-perl
libnet-pcap-perl
libnet-rawip-perl
libnet-server-perl
libnet-smtp-ssl-perl
libnet-snmp-perl
libnet-ssh2-perl
libnet-ssleay-perl:amd64
libnet-telnet-perl
libnet-tftp-perl
libnet-whois-ip-perl
libnet1:amd64
libnetcdf22:amd64
libnetfilter-conntrack3:amd64
libnetfilter-log1:amd64
libnetfilter-queue1:amd64
libnetpacket-perl
libnetpbm11t64:amd64
libnetsnmptrapd40t64:amd64
libnettle8t64:amd64
libnewt0.52:amd64
libnfc-bin
libnfc6:amd64
libnfnetlink0:amd64
libnfs14:amd64
libnfsidmap1:amd64
libnftables1:amd64
libnftnl11:amd64
libnghttp2-14:amd64
libnghttp3-9:amd64
libngtcp2-16:amd64
libngtcp2-crypto-gnutls8:amd64
libnice10:amd64
libnids1.21t64:amd64
libnl-3-200:amd64
libnl-genl-3-200:amd64
libnl-route-3-200:amd64
libnm0:amd64
libnma-common
libnma-gtk4-0:amd64
libnma0:amd64
libnode115:amd64
libnorm1t64:amd64
libnotify-bin
libnotify4:amd64
libnpth0t64:amd64
libnsl2:amd64
libnspr4:amd64
libnss-mdns:amd64
libnss-systemd:amd64
libnss-winbind:amd64
libnss3:amd64
libntfs-3g89t64:amd64
libnuma1:amd64
libnumber-bytes-human-perl
libnvme1t64
libobjc-14-dev:amd64
libobjc4:amd64
libobjenesis-java
libodbc2:amd64
libodbccr2:amd64
libodbcinst2:amd64
libodpic4:amd64
libogdi4.1:amd64
libogg0:amd64
libole-storage-lite-perl
libolecf1:amd64
libonig5:amd64
libonnx1t64:amd64
libonnxruntime1.21:amd64
liboobs-1-5:amd64
libopenal-data
libopenal1:amd64
libopenconnect5:amd64
libopencore-amrnb0:amd64
libopencore-amrwb0:amd64
libopenexr-3-1-30:amd64
libopenfec1:amd64
libopengl-dev:amd64
libopengl0:amd64
libopenh264-8:amd64
libopenjp2-7:amd64
libopenmpt0t64:amd64
libopenni2-0:amd64
libopus0:amd64
libopusfile0:amd64
liborc-0.4-0t64:amd64
libosgi-annotation-java
libosgi-compendium-java
libosgi-core-java
libosip2-15t64:amd64
libosmesa6:amd64
libosmosdr0:amd64
libostree-1-1:amd64
libout123-0t64:amd64
libp11-kit0:amd64
libpackage-deprecationmanager-perl
libpackage-stash-perl
libpackage-stash-xs-perl:amd64
libpackagekit-glib2-18:amd64
libpadwalker-perl
libpaho-mqtt1.3:amd64
libpam-gnome-keyring:amd64
libpam-modules:amd64
libpam-modules-bin
libpam-runtime
libpam-systemd:amd64
libpam-winbind:amd64
libpam0g:amd64
libpango-1.0-0:amd64
libpangocairo-1.0-0:amd64
libpangoft2-1.0-0:amd64
libpangomm-1.4-1v5:amd64
libpangomm-2.48-1t64:amd64
libpangoxft-1.0-0:amd64
libpaper-utils
libpaper2:amd64
libparallel-forkmanager-perl
libparams-classify-perl:amd64
libparams-util-perl
libparams-validate-perl:amd64
libparams-validationcompiler-perl
libparse-recdescent-perl
libparse-win32registry-perl
libparted-fs-resize0t64:amd64
libparted2t64:amd64
libpathplan4:amd64
libpcap-dev:amd64
libpcap0.8-dev:amd64
libpcap0.8t64:amd64
libpcaudio0:amd64
libpci3:amd64
libpciaccess0:amd64
libpcre2-16-0:amd64
libpcre2-32-0:amd64
libpcre2-8-0:amd64
libpcre2-posix3:amd64
libpcre3:amd64
libpcsclite1:amd64
libpdfbox-java
libpe1t64:amd64
libperl4-corelibs-perl
libperl5.40:amd64
libpfm4:amd64
libpgm-5.3-0t64:amd64
libphdi1:amd64
libphonenumber8:amd64
libpicocli-java
libpipeline1:amd64
libpipewire-0.3-0t64:amd64
libpipewire-0.3-common
libpipewire-0.3-modules:amd64
libpixman-1-0:amd64
libpkcs11-helper1t64:amd64
libpkgconf3:amd64
libplacebo349:amd64
libplexus-archiver-java
libplexus-cipher-java
libplexus-classworlds-java
libplexus-component-annotations-java
libplexus-container-default-java
libplexus-interpolation-java
libplexus-io-java
libplexus-sec-dispatcher-java
libplexus-utils2-java
libplist-2.0-4:amd64
libplymouth5:amd64
libpmem1:amd64
libpng16-16t64:amd64
libpocketsphinx3:amd64
libpocl2-common
libpocl2t64:amd64
libpod-parser-perl
libpolkit-agent-1-0:amd64
libpolkit-gobject-1-0:amd64
libpolyglot-maven-java
libpoppler-cpp2:amd64
libpoppler-glib8t64:amd64
libpoppler147:amd64
libpopt0:amd64
libportaudio2:amd64
libportmidi0:amd64
libpostproc58:amd64
libpotrace0:amd64
libpq5:amd64
libproc-processtable-perl:amd64
libproc2-0:amd64
libproguard-java
libproj25:amd64
libprotobuf-c1:amd64
libprotobuf32t64:amd64
libproxy1v5:amd64
libproxychains4:amd64
libpskc0t64:amd64
libpsl5t64:amd64
libpst4t64:amd64
libptexenc1:amd64
libpthreadpool0:amd64
libpulse-mainloop-glib0:amd64
libpulse0:amd64
libpwquality-common
libpwquality1:amd64
libpyside2-py3-5.15t64
libpyside6-py3-6.8
libpython2-stdlib:amd64
libpython2.7-minimal:amd64
libpython2.7-stdlib:amd64
libpython3-dev:amd64
libpython3-stdlib:amd64
libpython3.13:amd64
libpython3.13-dev:amd64
libpython3.13-minimal:amd64
libpython3.13-stdlib:amd64
libqcow1t64:amd64
libqdox-java
libqhull-r8.0:amd64
libqmi-glib5:amd64
libqmi-proxy
libqmi-utils
libqrencode4:amd64
libqrtr-glib0:amd64
libqscintilla2-qt5-15:amd64
libqscintilla2-qt5-l10n
libqt5charts5:amd64
libqt5core5t64:amd64
libqt5ct-common1.8
libqt5dbus5t64:amd64
libqt5designer5:amd64
libqt5gui5t64:amd64
libqt5help5:amd64
libqt5network5t64:amd64
libqt5opengl5t64:amd64
libqt5positioning5:amd64
libqt5printsupport5t64:amd64
libqt5qml5:amd64
libqt5qmlmodels5:amd64
libqt5quick5:amd64
libqt5quickwidgets5:amd64
libqt5script5:amd64
libqt5serialport5:amd64
libqt5sql5-sqlite:amd64
libqt5sql5t64:amd64
libqt5svg5:amd64
libqt5test5t64:amd64
libqt5waylandclient5:amd64
libqt5waylandcompositor5:amd64
libqt5webchannel5:amd64
libqt5webengine-data
libqt5webengine5:amd64
libqt5webenginecore5:amd64
libqt5webenginewidgets5:amd64
libqt5websockets5:amd64
libqt5widgets5t64:amd64
libqt5xml5t64:amd64
libqt5xmlpatterns5:amd64
libqt6core5compat6:amd64
libqt6core6t64:amd64
libqt6dbus6:amd64
libqt6gui6:amd64
libqt6multimedia6:amd64
libqt6network6:amd64
libqt6opengl6:amd64
libqt6openglwidgets6:amd64
libqt6positioning6:amd64
libqt6printsupport6:amd64
libqt6qml6:amd64
libqt6qmlmeta6:amd64
libqt6qmlmodels6:amd64
libqt6qmlworkerscript6:amd64
libqt6quick6:amd64
libqt6quickwidgets6:amd64
libqt6sql6:amd64
libqt6sql6-sqlite:amd64
libqt6svg6:amd64
libqt6svgwidgets6:amd64
libqt6test6:amd64
libqt6waylandclient6:amd64
libqt6waylandcompositor6:amd64
libqt6webchannel6:amd64
libqt6webengine6-data
libqt6webenginecore6:amd64
libqt6webenginecore6-bin
libqt6webenginewidgets6:amd64
libqt6widgets6:amd64
libqt6wlshellintegration6:amd64
libqt6xml6:amd64
libqtermwidget6-2:amd64
libquadmath0:amd64
libqwt-qt5-6
librabbitmq4:amd64
libradare2-5.0.0t64:amd64
libradare2-common
libradare2-dev
libradcli4
librados2
libraptor2-0:amd64
libraqm0:amd64
librav1e0.7:amd64
libraw1394-11:amd64
libraw23t64:amd64
librbd1
librdmacm1t64:amd64
libre2-11:amd64
libreadline8t64:amd64
libreadonly-perl
librecode3:amd64
libref-util-perl
libref-util-xs-perl
libreflectasm-java
libreflectasm-java-doc
libregexp-assemble-perl
libregexp-common-perl
libregexp-ipv6-perl
libregf1t64:amd64
libregfi1t64
librhino-java
librist4:amd64
librizin-common
librizin0:amd64
libroc0.4:amd64
librole-tiny-perl
librpc-xml-perl
librpm-sequoia-1:amd64
librpm10:amd64
librpmbuild10:amd64
librpmio10:amd64
librpmsign10:amd64
librsvg2-2:amd64
librsvg2-common:amd64
librtaudio7:amd64
librte-bus-pci25:amd64
librte-bus-vdev25:amd64
librte-eal25:amd64
librte-ethdev25:amd64
librte-hash25:amd64
librte-ip-frag25:amd64
librte-kvargs25:amd64
librte-log25:amd64
librte-mbuf25:amd64
librte-mempool25:amd64
librte-meter25:amd64
librte-net-bond25:amd64
librte-net25:amd64
librte-pci25:amd64
librte-rcu25:amd64
librte-ring25:amd64
librte-sched25:amd64
librte-telemetry25:amd64
librtlsdr0:amd64
librtmp1:amd64
librttopo1:amd64
librubberband2:amd64
libruby:amd64
libruby3.3:amd64
libsamplerate0:amd64
libsane-common
libsane1:amd64
libsasl2-2:amd64
libsasl2-modules:amd64
libsasl2-modules-db:amd64
libsbc1:amd64
libscca1t64:amd64
libsdl1.2debian:amd64
libsdl2-2.0-0:amd64
libsdl2-image-2.0-0:amd64
libsdl2-mixer-2.0-0:amd64
libsdl2-ttf-2.0-0:amd64
libseccomp2:amd64
libsecret-1-0:amd64
libsecret-common
libselinux1:amd64
libsemanage-common
libsemanage2:amd64
libsensors-config
libsensors5:amd64
libsepol2:amd64
libserd-0-0:amd64
libserf-1-1:amd64
libserialport0:amd64
libservlet-api-java
libsframe1:amd64
libsharpyuv0:amd64
libshiboken2-py3-5.15t64
libshiboken6-py3-6.8
libshine3:amd64
libshout3:amd64
libsidplay1v5:amd64
libsigc++-2.0-0v5:amd64
libsigc++-3.0-0:amd64
libsigscan1t64:amd64
libsigsegv2:amd64
libsimple-http-java
libsisu-inject-java
libsisu-plexus-java
libslang2:amd64
libslf4j-java
libslirp0:amd64
libsm-dev:amd64
libsm6:amd64
libsmali-java
libsmartcols1:amd64
libsmb2-6
libsmbclient0:amd64
libsmdev1t64:amd64
libsmi2t64:amd64
libsmraw1t64:amd64
libsnappy-java
libsnappy-jni
libsnappy1v5:amd64
libsndfile1:amd64
libsnmp-base
libsnmp-perl
libsnmp40t64:amd64
libsoapysdr0.8:amd64
libsocket6-perl
libsodium23:amd64
libsombok3:amd64
libsonic0:amd64
libsord-0-0:amd64
libsort-naturally-perl
libsoundtouch1:amd64
libsoup-2.4-1:amd64
libsoup-3.0-0:amd64
libsoup-3.0-common
libsoup2.4-common
libsource-highlight-common
libsource-highlight4t64:amd64
libsox-fmt-alsa:amd64
libsox-fmt-base:amd64
libsox3:amd64
libsoxr0:amd64
libspa-0.2-bluetooth:amd64
libspa-0.2-modules:amd64
libspandsp2t64:amd64
libspatialite8t64:amd64
libspdlog-dev:amd64
libspdlog1.15:amd64
libspecio-perl
libspectre1:amd64
libspeechd-module0:amd64
libspeechd2:amd64
libspeex1:amd64
libspeexdsp1:amd64
libsphinxbase3t64:amd64
libspice-server1:amd64
libspiffy-perl
libspreadsheet-parseexcel-perl
libspreadsheet-writeexcel-perl
libsqlcipher1:amd64
libsqlite3-0:amd64
libsratom-0-0:amd64
libsrt1.5-gnutls:amd64
libsrtp2-1:amd64
libss2:amd64
libssh-4:amd64
libssh2-1t64:amd64
libssl3t64:amd64
libstartup-notification0:amd64
libstdc++-14-dev:amd64
libstdc++6:amd64
libstemmer0d:amd64
libstoken1t64:amd64
libstring-crc32-perl
libstring-random-perl
libstringtemplate-java
libstrongswan
libstrongswan-standard-plugins
libsub-exporter-perl
libsub-exporter-progressive-perl
libsub-identify-perl
libsub-install-perl
libsub-name-perl:amd64
libsub-quote-perl
libsvn1:amd64
libsvtav1enc2:amd64
libswresample5:amd64
libswscale8:amd64
libswt-cairo-gtk-4-jni
libswt-gtk-4-java
libswt-gtk-4-jni
libsybdb5:amd64
libsyn123-0t64:amd64
libsynctex2:amd64
libsystemd-dev:amd64
libsystemd-shared:amd64
libsystemd0:amd64
libsz2:amd64
libtag-c2:amd64
libtag2:amd64
libtalloc2:amd64
libtasn1-6:amd64
libtbb12:amd64
libtbbbind-2-5:amd64
libtbbmalloc2:amd64
libtcl8.6:amd64
libtdb1:amd64
libteamdctl0:amd64
libteckit0:amd64
libtecla1t64:amd64
libterm-readkey-perl
libterm-readline-gnu-perl
libtevent0t64:amd64
libtexlua53-5:amd64
libtext-charwidth-perl:amd64
libtext-csv-perl
libtext-csv-xs-perl:amd64
libtext-iconv-perl:amd64
libtext-wrapi18n-perl
libthai-data
libthai0:amd64
libtheora0:amd64
libtheoradec1:amd64
libtheoraenc1:amd64
libthrift-0.19.0t64:amd64
libthrift-dev:amd64
libthunarx-3-0:amd64
libtie-ixhash-perl
libtiff6:amd64
libtimedate-perl
libtinfo6:amd64
libtirpc-common
libtirpc3t64:amd64
libtk8.6:amd64
libtomcrypt1:amd64
libtommath1:amd64
libtry-tiny-perl
libts0t64:amd64
libtsan2:amd64
libtsk19t64:amd64
libtss2-esys-3.0.2-0t64:amd64
libtss2-mu-4.0.1-0t64:amd64
libtss2-sys1t64:amd64
libtss2-tcti-cmd0t64:amd64
libtss2-tcti-device0t64:amd64
libtss2-tcti-libtpms0t64:amd64
libtss2-tcti-mssim0t64:amd64
libtss2-tcti-spi-helper0t64:amd64
libtss2-tcti-swtpm0t64:amd64
libtss2-tctildr0t64:amd64
libtumbler-1-0t64:amd64
libturbojpeg0:amd64
libtwolame0:amd64
libtypes-serialiser-perl
libubertooth1:amd64
libubsan1:amd64
libuchardet0:amd64
libudev1:amd64
libudfread0:amd64
libudisks2-0:amd64
libuhd4.8.0:amd64
libunbound8:amd64
libunibreak6:amd64
libunicode-linebreak-perl
libunicode-map-perl
libunistring5:amd64
libunsafessl1.0.2:amd64
libunwind8:amd64
libupower-glib3:amd64
liburcu8t64:amd64
liburi-perl
liburing2:amd64
liburiparser1:amd64
libusb-0.1-4:amd64
libusb-1.0-0:amd64
libusb3380-0t64:amd64
libusbmuxd-2.0-7:amd64
libusbredirparser1t64:amd64
libutempter0:amd64
libutf8proc3:amd64
libuuid-perl
libuuid1:amd64
libuv1-dev:amd64
libuv1t64:amd64
libv4l-0t64:amd64
libv4lconvert0t64:amd64
libva-drm2:amd64
libva-x11-2:amd64
libva2:amd64
libvariable-magic-perl
libvdeplug2t64:amd64
libvdpau-va-gl1:amd64
libvdpau1:amd64
libvhdi1:amd64
libvidstab1.1:amd64
libvirglrenderer1:amd64
libvisual-0.4-0:amd64
libvmdk1:amd64
libvo-aacenc0:amd64
libvo-amrwbenc0:amd64
libvoikko1:amd64
libvolk-bin
libvolk-dev:amd64
libvolk3.2:amd64
libvolume-key1:amd64
libvorbis0a:amd64
libvorbisenc2:amd64
libvorbisfile3:amd64
libvpl2
libvpx9:amd64
libvsapm1:amd64
libvshadow1t64:amd64
libvslvm1t64:amd64
libvte-2.91-0:amd64
libvte-2.91-common
libvulkan1:amd64
libwacom-common
libwacom9:amd64
libwagon-file-java
libwagon-http-java
libwagon-provider-api-java
libwavpack1:amd64
libwayland-client0:amd64
libwayland-cursor0:amd64
libwayland-egl1:amd64
libwayland-server0:amd64
libwbclient0:amd64
libwebkit2gtk-4.1-0:amd64
libwebp7:amd64
libwebpdemux2:amd64
libwebpmux3:amd64
libwebrtc-audio-processing-1-3:amd64
libwebsocket-api-java
libwebsockets19t64:amd64
libwhereami0:amd64
libwildmidi2:amd64
libwine:amd64
libwinpr3-3:amd64
libwireplumber-0.5-0:amd64
libwireshark-data
libwireshark18:amd64
libwiretap15:amd64
libwmflite-0.2-7:amd64
libwnck-3-0:amd64
libwnck-3-common
libwoff1:amd64
libwrap0:amd64
libwsutil16:amd64
libwtmpdb0:amd64
libwww-mechanize-perl
libwww-perl
libwww-robotrules-perl
libwxbase3.2-1t64:amd64
libwxgtk-gl3.2-1t64:amd64
libwxgtk3.2-1t64:amd64
libx11-6:amd64
libx11-data
libx11-dev:amd64
libx11-protocol-perl
libx11-xcb1:amd64
libx264-164:amd64
libx265-215:amd64
libx86-1:amd64
libxar1
libxatracker2:amd64
libxau-dev:amd64
libxau6:amd64
libxaw7:amd64
libxbean-reflect-java
libxcb-cursor0:amd64
libxcb-damage0:amd64
libxcb-dri2-0:amd64
libxcb-dri3-0:amd64
libxcb-glx0:amd64
libxcb-icccm4:amd64
libxcb-image0:amd64
libxcb-keysyms1:amd64
libxcb-present0:amd64
libxcb-randr0:amd64
libxcb-render-util0:amd64
libxcb-render0:amd64
libxcb-shape0:amd64
libxcb-shm0:amd64
libxcb-sync1:amd64
libxcb-util1:amd64
libxcb-xfixes0:amd64
libxcb-xinerama0:amd64
libxcb-xinput0:amd64
libxcb-xkb1:amd64
libxcb-xv0:amd64
libxcb1:amd64
libxcb1-dev:amd64
libxcomposite1:amd64
libxcursor1:amd64
libxcvt0:amd64
libxdamage1:amd64
libxdmcp-dev:amd64
libxdmcp6:amd64
libxdo3:amd64
libxdp1:amd64
libxerces-c3.2t64:amd64
libxerces2-java
libxext-dev:amd64
libxext6:amd64
libxfce4panel-2.0-4
libxfce4ui-2-0:amd64
libxfce4ui-common
libxfce4ui-utils
libxfce4util-bin
libxfce4util-common
libxfce4util7:amd64
libxfce4windowing-0-0:amd64
libxfce4windowing-common
libxfconf-0-3:amd64
libxfixes3:amd64
libxfont2:amd64
libxft2:amd64
libxi6:amd64
libxinerama1:amd64
libxkbcommon-x11-0:amd64
libxkbcommon0:amd64
libxkbfile1:amd64
libxkbregistry0:amd64
libxklavier16:amd64
libxm4:amd64
libxml++2.6-2v5:amd64
libxml-commons-external-java
libxml-commons-resolver1.1-java
libxml-dom-perl
libxml-parser-perl
libxml-perl
libxml-regexp-perl
libxml-twig-perl
libxml-writer-perl
libxml-xpathengine-perl
libxml2:amd64
libxml2-dev:amd64
libxml2-utils
libxmlb2:amd64
libxmlsec1t64:amd64
libxmlsec1t64-openssl:amd64
libxmlunit-java
libxmp4:amd64
libxmu6:amd64
libxmuu1:amd64
libxnnpack0.20241108:amd64
libxnvctrl0:amd64
libxpm4:amd64
libxpp3-java
libxpresent1:amd64
libxrandr2:amd64
libxrender1:amd64
libxres1:amd64
libxshmfence1:amd64
libxslt1.1:amd64
libxss1:amd64
libxstream-java
libxstring-perl:amd64
libxt-dev:amd64
libxt6t64:amd64
libxtables12:amd64
libxtrx0:amd64
libxtrxdsp0:amd64
libxtrxll0t64:amd64
libxtst6:amd64
libxv1:amd64
libxvidcore4:amd64
libxvmc1:amd64
libxxf86dga1:amd64
libxxf86vm1:amd64
libxxhash-dev:amd64
libxxhash0:amd64
libxz-java
libyajl2:amd64
libyaml-0-2:amd64
libyaml-snake-java
libyaml-tiny-perl
libyara10:amd64
libyelp0:amd64
libyuv0:amd64
libz-mingw-w64
libz3-4:amd64
libz3-dev:amd64
libzbar0t64:amd64
libze1:amd64
libzimg2:amd64
libzip-dev:amd64
libzip5:amd64
libzix-0-0:amd64
libzmq5:amd64
libzopfli1
libzstd1:amd64
libzvbi-common
libzvbi0t64:amd64
libzxing3:amd64
libzzip-0-13t64:amd64
lightdm
lightdm-gtk-greeter
lightdm-gtk-greeter-settings
lighttpd
lighttpd-mod-deflate
lighttpd-mod-openssl
ligolo-ng
ligolo-ng-common-binaries
lime-forensics-dkms
limesuite-udev
linkedin2username
linux-base
linux-exploit-suggester
linux-headers-6.12.33+kali-amd64
linux-headers-6.12.33+kali-common
linux-headers-amd64
linux-image-6.12.25-amd64
linux-image-6.12.33+kali-amd64
linux-image-amd64
linux-kbuild-6.12.33+kali
linux-libc-dev
linux-sysctl-defaults
llvm-18
llvm-18-dev
llvm-18-linker-tools
llvm-18-runtime
llvm-18-tools
llvm-19
llvm-19-dev
llvm-19-linker-tools
llvm-19-runtime
llvm-19-tools
llvm-spirv-18
lm-sensors
lmodern
locales
locales-all
login
login.defs
logrotate
logsave
lrzsz
lsb-release
lsof
luit
lvm2
lynis
lz4
lziprecover
lzop
m4
mac-robber
macchanger
magicrescue
mailcap
make
maltego
maltego-teeth
man-db
manpages
manpages-dev
mariadb-client
mariadb-client-core
mariadb-common
mariadb-plugin-provider-bzip2
mariadb-plugin-provider-lz4
mariadb-plugin-provider-lzma
mariadb-plugin-provider-lzo
mariadb-plugin-provider-snappy
mariadb-server
mariadb-server-compat
mariadb-server-core
maryam
maskprocessor
masscan
massdns
mate-calc
mate-calc-common
mate-polkit
mate-polkit-common
mawk
mc
mc-data
mdbtools
mdk3
mdk4
media-types
medusa
memdump
menu
mercurial
mercurial-common
merlin-agent
merlin-server
mesa-libgallium:amd64
mesa-va-drivers:amd64
mesa-vdpau-drivers:amd64
mesa-vulkan-drivers:amd64
metacam
metagoofil
metasploit-framework
mfcuk
mfoc
mfterm
mimikatz
mingw-w64
mingw-w64-common
mingw-w64-i686-dev
mingw-w64-tools
mingw-w64-x86-64-dev
minicom
miredo
missidentify
mitm6
mitmproxy
mobile-broadband-provider-info
modemmanager
mongo-tools
mono-4.0-gac
mono-csharp-shell
mono-devel
mono-gac
mono-mcs
mono-runtime
mono-runtime-common
mono-runtime-sgen
mono-xbuild
mosquitto
mount
mousepad
mpg123
msfpc
mssqlpwner
mtd-utils
multiforcer
multimac
multimon-ng
mupdf-tools
mxcheck
myrescue
mysql-common
naabu
name-that-hash
nano
nasm
nasty
nautilus-extension-gnome-terminal:amd64
nbtscan
nbtscan-unixwiz
ncat
ncat-w32
ncompress
ncrack
ncurses-base
ncurses-bin
ncurses-hexedit
ncurses-term
ndiff
needrestart
neo4j
net-tools
netbase
netcat-traditional
netdiscover
netexec
netmask
netpbm
netscanner
netsed
netsniff-ng
netstandard-targeting-pack-2.1
netwag
network-manager
network-manager-applet
network-manager-gnome
network-manager-l10n
network-manager-l2tp
network-manager-l2tp-gnome
network-manager-openconnect
network-manager-openconnect-gnome
network-manager-openvpn
network-manager-openvpn-gnome
network-manager-pptp
network-manager-pptp-gnome
network-manager-vpnc
network-manager-vpnc-gnome
netwox
nextnet
nfs-common
nftables
nginx
nginx-common
ngrep
nikto
nipper-ng
nishang
nm-connection-editor
nmap
nmap-common
nmapsi4
node-acorn
node-balanced-match
node-brace-expansion
node-cjs-module-lexer
node-corepack
node-fortawesome-fontawesome-free
node-jquery
node-minimatch
node-normalize.css
node-undici
node-xtend
nodejs
nodejs-doc
notus-scanner
nsis
nsis-common
ntfs-3g
nuclei
numba-doc
obsidian
ocl-icd-libopencl1:amd64
oclgausscrack
octicons
odat
offsec-awae-python2
ohrwurm
oinkmaster
ollydbg
onboard
onboard-common
onboard-data
onesixtyone
openconnect
openjdk-11-jre:amd64
openjdk-11-jre-headless:amd64
openjdk-21-jdk:amd64
openjdk-21-jdk-headless:amd64
openjdk-21-jre:amd64
openjdk-21-jre-headless:amd64
openocd
opensc
opensc-pkcs11:amd64
openssh-client
openssh-client-gssapi
openssh-client-ssh1
openssh-server
openssh-sftp-server
openssl
openssl-provider-legacy
opentaxii
openvas-scanner
openvpn
ophcrack
ophcrack-cli
oracle-instantclient-basic
oracle-instantclient-devel
orca
os-prober
oscanner
ospd-openvas
osrframework
outguess
ovmf
owasp-mantra-ff
owl
p0f
p11-kit
p11-kit-modules:amd64
pack
pack2
pacu
padbuster
pahole
parallel
parole
paros
parsero
parted
pasco
passdetective
passing-the-hash
passwd
patator
patch
pavucontrol
payloadsallthethings
pci.ids
pciutils
pcscd
pdf-parser
pdfcrack
pdfgrep
pdfid
peass
peek
peirates
perl
perl-base
perl-cisco-copyconfig
perl-modules-5.40
perl-openssl-defaults:amd64
perl-tk
pev
pgcli
phishery
photon
php
php-common
php-mysql
php-sqlite3
php8.4
php8.4-cli
php8.4-common
php8.4-mysql
php8.4-opcache
php8.4-readline
php8.4-sqlite3
phpggc
phpsploit
pinentry-curses
pinentry-gnome3
pipal
pipewire:amd64
pipewire-bin
pipewire-pulse
pipx
pixiewps
pkexec
pkgconf:amd64
pkgconf-bin
plaso
plocate
plymouth
plymouth-label
pnscan
pocketsphinx-en-us
pocl-opencl-icd:amd64
pocsuite3
polenum
policycoreutils
polkitd
pompem
poppler-data
portspoof
poshc2
postgresql
postgresql-17
postgresql-17-pg-gvm
postgresql-client-17
postgresql-client-common
postgresql-common
powercat
powermgmt-base
powershell
powershell-empire
powersploit
ppp
pptp-linux
preview-latex-style
princeprocessor
procps
proguard-cli
proj-bin
proj-data
protos-sip
proxify
proximoth
proxmark3
proxmark3-common
proxmark3-firmwares
proxychains4
proxytunnel
pry
pskracker
pskracker-data
psmisc
pspy
pst-utils
ptunnel
publicsuffix
pv
pwgen
pwnat
pwncat
pybind11-dev
pyflakes3
pyinstxtractor
pylint
pyqt5-dev-tools
pyqt6-dev-tools
python-apt-common
python-asyncssh-doc
python-babel-localedata
python-cffi
python-cffi-backend
python-is-python3
python-matplotlib-data
python-odf-doc
python-odf-tools
python-tables-data
python-tinycss2-common
python2
python2-minimal
python2.7
python2.7-minimal
python3
python3-aadict
python3-aardwolf
python3-about-time
python3-acstore
python3-adblockparser
python3-adns
python3-aesedb
python3-aiocmd
python3-aioconsole
python3-aiodns
python3-aiofiles
python3-aioftp
python3-aiohappyeyeballs
python3-aiohttp
python3-aiohttp-apispec
python3-aiohttp-jinja2
python3-aiohttp-security
python3-aiohttp-session
python3-aiomultiprocess
python3-aioquic
python3-aiosignal
python3-aiosmb
python3-aiosqlite
python3-aiowinreg
python3-ajpy
python3-alabaster
python3-alembic
python3-alive-progress
python3-altgraph
python3-amqp
python3-aniso8601
python3-annotated-types
python3-antlr4
python3-anyio
python3-apispec
python3-apispec-webframeworks
python3-apt
python3-arc4
python3-argcomplete
python3-argon2
python3-args
python3-arpy
python3-arrow
python3-artifacts
python3-asciitree
python3-asgiref
python3-asn1crypto
python3-asn1tools
python3-asset
python3-asteval
python3-astroid
python3-asttokens
python3-asyauth
python3-async-timeout
python3-asyncssh
python3-asysocks
python3-attr
python3-autobahn
python3-autocommand
python3-automat
python3-awscrt
python3-babel
python3-backoff
python3-base58
python3-base62
python3-base91
python3-bcrypt
python3-bidict
python3-billiard
python3-binwalk
python3-bitstruct
python3-blackduck
python3-bleach
python3-blinker
python3-blosc
python3-bluepy
python3-bluez
python3-boto3
python3-botocore
python3-bottle
python3-bottleneck
python3-brlapi:amd64
python3-brotli
python3-bs4
python3-bson
python3-bson-ext:amd64
python3-cachecontrol
python3-cachetools
python3-cairo
python3-cairocffi
python3-capstone
python3-cassandra
python3-cbor
python3-celery
python3-censys
python3-cerberus
python3-certifi
python3-cffi
python3-cffi-backend:amd64
python3-cfscrape
python3-chardet
python3-charset-normalizer
python3-cheroot
python3-cherrypy-cors
python3-cherrypy3
python3-ciphey
python3-cipheycore
python3-cipheydists
python3-cli-helpers
python3-click
python3-click-didyoumean
python3-click-plugins
python3-click-repl
python3-clint
python3-cloudpickle
python3-cloudscraper
python3-cmd2
python3-colorama
python3-colorlog
python3-commandparse
python3-commonmark
python3-configargparse
python3-configobj
python3-constantly
python3-contourpy
python3-coreapi
python3-coreschema
python3-cpe
python3-cpuinfo
python3-crcelk
python3-croniter
python3-cryptography
python3-cssselect
python3-cssselect2
python3-cstruct
python3-ctypescrypto
python3-cups:amd64
python3-cupshelpers
python3-cvss
python3-cx-oracle
python3-cycler
python3-dacite
python3-dask
python3-dateutil
python3-dbus
python3-decorator
python3-defusedxml
python3-deprecated
python3-dev
python3-dfdatetime
python3-dfvfs
python3-dfwinreg
python3-dhcplib
python3-dicttoxml
python3-dill
python3-dissect.cstruct
python3-distlib
python3-distorm3
python3-distributed
python3-distro
python3-django
python3-django-appconf
python3-django-auditlog
python3-django-celery-results
python3-django-crispy-forms
python3-django-crum
python3-django-dbbackup
python3-django-environ
python3-django-extensions
python3-django-extra-views
python3-django-fieldsignals
python3-django-filters
python3-django-guardian
python3-django-imagekit
python3-django-multiselectfield
python3-django-polymorphic
python3-django-ratelimit
python3-django-restframework-guardian
python3-django-split-settings
python3-django-tagging
python3-django-tagulous
python3-django-watson
python3-djangorestframework
python3-djangorestframework-spectacular
python3-dnslib
python3-dnspython
python3-docker
python3-docopt
python3-docutils
python3-docx
python3-docxcompose
python3-docxtpl
python3-donut
python3-dotenv
python3-dploot
python3-drf-spectacular-sidecar-nonfree
python3-drf-yasg-nonfree
python3-dronekit
python3-dropbox
python3-dsinternals
python3-dsnap
python3-dtfabric
python3-duckpy
python3-easygui
python3-ecdsa
python3-elastic-transport
python3-elasticsearch
python3-email-validator
python3-emailahoy3
python3-enchant
python3-engineio
python3-envs
python3-ephem
python3-et-xmlfile
python3-evdev
python3-eventlet
python3-executing
python3-exifread
python3-extproxy
python3-fake-factory
python3-fake-useragent
python3-faraday-agent-parameters-types
python3-faraday-plugins
python3-fastapi
python3-fastjsonschema
python3-feedparser
python3-filebytes
python3-filedepot
python3-filelock
python3-filteralchemy
python3-fire
python3-flake8
python3-flasgger
python3-flask
python3-flask-celery-helper
python3-flask-classful
python3-flask-cors
python3-flask-httpauth
python3-flask-jsglue
python3-flask-kvsession
python3-flask-limiter
python3-flask-login
python3-flask-mail
python3-flask-principal
python3-flask-restful
python3-flask-restx
python3-flask-socketio
python3-flask-sqlalchemy
python3-flaskext.wtf
python3-flatbuffers
python3-fleep
python3-flor
python3-fontawesomefree
python3-fonttools
python3-fpdf
python3-fqdn
python3-freetype
python3-freezegun
python3-frozenlist
python3-fs
python3-fsapfs:amd64
python3-fsspec
python3-fuzzywuzzy
python3-gattlib
python3-gdal
python3-gensim
python3-geoip:amd64
python3-geoip2
python3-geomet
python3-gevent
python3-gevent-websocket
python3-gexf
python3-gi
python3-gi-cairo
python3-git
python3-gitdb
python3-github
python3-gitlab
python3-globre
python3-gmplot
python3-gnupg
python3-google-api-core
python3-google-auth
python3-google-auth-httplib2
python3-googleapi
python3-googleapis-common-protos
python3-googlesearch
python3-gpg
python3-gps
python3-gps3
python3-grapheme
python3-graphviz
python3-greenlet
python3-gridfs
python3-gssapi
python3-gunicorn
python3-gvm
python3-h11
python3-h2
python3-hamcrest
python3-hpack
python3-html2text
python3-html5lib
python3-httpagentparser
python3-httpcore
python3-httplib2
python3-httpx
python3-humanize
python3-hupper
python3-hypercorn
python3-hyperframe
python3-hyperlink
python3-idna
python3-imagesize
python3-imapclient
python3-impacket
python3-importlib-metadata
python3-importlib-resources
python3-incremental
python3-infinity
python3-inflect
python3-inflection
python3-iniconfig
python3-invoke
python3-ip2proxy
python3-ipwhois
python3-ipy
python3-ipython
python3-isc-dhcp-leases
python3-isoduration
python3-isort
python3-itsdangerous
python3-itypes
python3-jaraco.collections
python3-jaraco.context
python3-jaraco.functools
python3-jaraco.text
python3-jedi
python3-jefferson
python3-jenkins
python3-jinja2
python3-jira
python3-jmespath
python3-joblib
python3-jq
python3-jsmin
python3-json-log-formatter
python3-json-pointer
python3-json5
python3-jsonschema
python3-jsonschema-specifications
python3-jupyter-core
python3-jwcrypto
python3-jwt
python3-kaitaistruct
python3-keystone-engine
python3-kismetcapturebtgeiger
python3-kismetcapturefreaklabszigbee
python3-kismetcapturertl433
python3-kismetcapturertladsb
python3-kismetcapturertlamr
python3-kiwisolver
python3-kombu
python3-langdetect
python3-lark
python3-ldap
python3-ldap3
python3-ldap3-bleeding-edge
python3-ldapdomaindump
python3-ldb
python3-legacy-cgi
python3-legacycrypt
python3-levenshtein
python3-libarchive-c
python3-libbde:amd64
python3-libcreg
python3-libesedb
python3-libevt:amd64
python3-libevtx:amd64
python3-libewf
python3-libfsext
python3-libfshfs
python3-libfsntfs:amd64
python3-libfsxfs
python3-libfvde:amd64
python3-libfwnt
python3-libfwsi
python3-liblnk
python3-libluksde
python3-libmsiecf:amd64
python3-libnmap
python3-libolecf:amd64
python3-libqcow:amd64
python3-libregf:amd64
python3-libscca
python3-libsigscan:amd64
python3-libsmdev:amd64
python3-libsmraw:amd64
python3-libtaxii
python3-libvhdi:amd64
python3-libvmdk:amd64
python3-libvshadow:amd64
python3-libvslvm:amd64
python3-lief
python3-limits
python3-linkify-it
python3-llvmlite
python3-lml
python3-locket
python3-log-symbols
python3-logilab-common
python3-loguru
python3-logutils
python3-louis
python3-lsassy
python3-lxml:amd64
python3-lz4
python3-lzallright
python3-macholib
python3-magic
python3-magic-ahupp
python3-mako
python3-manuf
python3-markdown
python3-markdown-it
python3-markdown2
python3-markupsafe
python3-marshmallow
python3-marshmallow-sqlalchemy
python3-masky
python3-matplotlib
python3-matplotlib-inline
python3-maxminddb
python3-mccabe
python3-md2pdf
python3-mdit-py-plugins
python3-mdurl
python3-mechanize
python3-memcache
python3-metaconfig
python3-minidump
python3-minikerberos
python3-minimal
python3-mistune
python3-mitmproxy-rs
python3-mitmproxy-wireguard
python3-mnemonic
python3-mock
python3-monotonic
python3-more-itertools
python3-more-termcolor
python3-mpmath
python3-msgpack
python3-msldap
python3-multi-key-dict
python3-multidict
python3-multipart
python3-mypy-boto3-ebs
python3-mypy-extensions
python3-mysqldb
python3-myst-parser
python3-nacl
python3-nassl
python3-nbformat
python3-neo4j
python3-neobolt
python3-neotime
python3-netaddr
python3-netifaces:amd64
python3-netmiko
python3-networkx
python3-newt:amd64
python3-nmap
python3-nplusone
python3-ntc-templates
python3-ntlm-auth
python3-numba
python3-numexpr
python3-numpy
python3-numpy-dev:amd64
python3-oauthlib
python3-obfuscator
python3-odf
python3-olefile
python3-openai
python3-opengl
python3-openid
python3-openpyxl
python3-openssl
python3-ordered-set
python3-oscrypto
python3-outcome
python3-packageurl
python3-packaging
python3-paho-mqtt
python3-pandas
python3-pandas-lib:amd64
python3-paramiko
python3-parso
python3-partd
python3-passlib
python3-passwordmeter
python3-paste
python3-pastedeploy
python3-pastedeploy-tpl
python3-pastescript
python3-pathspec
python3-pbkdf2
python3-pbr
python3-pcapy
python3-pefile
python3-pem
python3-pexpect
python3-pgspecial
python3-phonenumbers
python3-phpserialize
python3-pil:amd64
python3-pil.imagetk:amd64
python3-pilkit
python3-ping3
python3-pip
python3-pip-whl
python3-pkg-resources
python3-plaso
python3-plaster
python3-plaster-pastedeploy
python3-platformdirs
python3-playwright
python3-plotext
python3-plotly
python3-pluggy
python3-pluginbase
python3-ply
python3-png
python3-policyuniverse
python3-pooch
python3-portend
python3-pptx
python3-prettytable
python3-priority
python3-prompt-toolkit
python3-propcache
python3-proto-plus
python3-protobuf
python3-psutil
python3-psycogreen
python3-psycopg
python3-psycopg-c
python3-psycopg2
python3-ptyprocess
python3-publicsuffix2
python3-publicsuffixlist
python3-pure-eval
python3-py
python3-py-sneakers
python3-pyasn1
python3-pyasn1-modules
python3-pyasyncore
python3-pycaes
python3-pycares
python3-pycodestyle
python3-pycognito
python3-pycparser
python3-pycriu
python3-pycryptodome
python3-pycurl
python3-pydantic
python3-pydantic-core
python3-pydispatch
python3-pydot
python3-pydotplus
python3-pydyf
python3-pyee
python3-pyexcel
python3-pyexcel-io
python3-pyexcel-ods
python3-pyexcel-text
python3-pyexcel-xls
python3-pyexcel-xlsx
python3-pyexploitdb
python3-pyfatfs
python3-pyfcrypto
python3-pyfiglet
python3-pyflakes
python3-pyfsfat
python3-pygame
python3-pygccxml
python3-pygit2
python3-pygments
python3-pygraphviz
python3-pyinotify
python3-pyinstaller
python3-pylnk3
python3-pylsqpack
python3-pymavlink
python3-pymetasploit3
python3-pymongo
python3-pymongo-ext:amd64
python3-pymssql
python3-pymysql
python3-pynfsclient
python3-pynput
python3-pyodbc:amd64
python3-pyotp
python3-pyparsing
python3-pypdf
python3-pyperclip
python3-pyperscan
python3-pyphdi
python3-pyphen
python3-pyppeteer
python3-pypsrp
python3-pypykatz
python3-pyqrcode
python3-pyqt5
python3-pyqt5.qsci
python3-pyqt5.qtchart
python3-pyqt5.qtopengl
python3-pyqt5.qwt
python3-pyqt5.sip
python3-pyqt6
python3-pyqt6.sip
python3-pyqtgraph
python3-pyquery
python3-pyramid
python3-pyregfi
python3-pyric
python3-pyshark
python3-pyshodan
python3-pyside2.qtcore
python3-pyside2.qtgui
python3-pyside2.qtwidgets
python3-pysmi
python3-pysnmp4
python3-pyspnego
python3-pytest
python3-python-multipart
python3-pythonping
python3-pytz
python3-pyu2f
python3-pyuserinput
python3-pyvirtualdisplay
python3-pyvnc
python3-pyvsapm
python3-pywebcopy
python3-pywerview
python3-pywhat
python3-pyzipper
python3-pyzstd
python3-qasync
python3-qrcode
python3-quart
python3-rapidfuzz
python3-rarfile
python3-ratelimit
python3-recommonmark
python3-redis
python3-referencing
python3-regex
python3-rel
python3-reportlab
python3-repoze.lru
python3-requests
python3-requests-file
python3-requests-futures
python3-requests-ntlm
python3-requests-oauthlib
python3-requests-toolbelt
python3-responses
python3-retry
python3-retrying
python3-rfc3339-validator
python3-rfc3986-validator
python3-rfc3987
python3-rich
python3-rjsmin
python3-rlpycairo
python3-roguehostapd
python3-roman
python3-routes
python3-rpds-py
python3-rq
python3-rsa
python3-ruamel.yaml
python3-ruamel.yaml.clib
python3-rzpipe
python3-s3transfer
python3-samba
python3-sarge
python3-scapy
python3-schema
python3-scipy
python3-scp
python3-secretsocks
python3-secure
python3-selenium
python3-serial
python3-serial-asyncio
python3-service-identity
python3-setproctitle:amd64
python3-setuptools
python3-setuptools-whl
python3-sgmllib3k
python3-sh
python3-shodan
python3-shtab
python3-sigma
python3-simple-rest-client
python3-simple-websocket
python3-simplejson
python3-simplekv
python3-six
python3-sklearn
python3-sklearn-lib:amd64
python3-slowapi
python3-slugify
python3-smart-open
python3-smb
python3-smbc
python3-smmap
python3-smoke-zephyr
python3-snappy
python3-sniffio
python3-snowballstemmer
python3-social-auth-core
python3-social-django
python3-socketio
python3-socks
python3-sortedcontainers
python3-soupsieve
python3-speechd
python3-sphinx
python3-sphinx-rtd-theme
python3-sphinxcontrib.jquery
python3-spinners
python3-sqlalchemy
python3-sqlalchemy-ext:amd64
python3-sqlalchemy-schemadisplay
python3-sqlalchemy-utc
python3-sqlalchemy-utils
python3-sqlparse
python3-ssdeep
python3-stack-data
python3-standard-imghdr
python3-starlette
python3-status
python3-stem
python3-stix2
python3-stix2-patterns
python3-stone
python3-stringdist
python3-structlog
python3-suds
python3-svglib
python3-swagger-spec-validator
python3-sympy
python3-syslog-rfc5424-formatter
python3-tables
python3-tables-lib
python3-tabulate
python3-talloc:amd64
python3-tblib
python3-tdb
python3-tempita
python3-tempora
python3-tenacity
python3-termcolor
python3-terminaltables
python3-textfsm
python3-texttable
python3-threadpoolctl
python3-thrift
python3-tinycss2
python3-tinydb
python3-titlecase
python3-tk:amd64
python3-tld
python3-tldextract
python3-tls-parser
python3-tlsh:amd64
python3-toml
python3-tomlkit
python3-toolz
python3-tornado
python3-tqdm
python3-traitlets
python3-translationstring
python3-treelib
python3-trie
python3-trio
python3-trio-websocket
python3-tsk:amd64
python3-twisted
python3-txaio
python3-typeguard
python3-typeshed
python3-typing-extensions
python3-tz
python3-tzlocal
python3-u-msgpack
python3-ubireader
python3-ubjson
python3-uc-micro
python3-ufolib2
python3-uhd
python3-ujson:amd64
python3-unicodedata2
python3-unicrypto
python3-unidecode
python3-uritemplate
python3-urllib3
python3-urwid
python3-usb
python3-userpath
python3-uvicorn
python3-uvloop
python3-vadersentiment
python3-validators
python3-venusian
python3-venv
python3-vine
python3-virtualenv
python3-vobject
python3-vulners
python3-wcwidth
python3-webargs
python3-webcolors
python3-webencodings
python3-webob
python3-websocket
python3-websockets
python3-websockify
python3-werkzeug
python3-wget
python3-wheel
python3-whois
python3-winacl
python3-wordcloud
python3-wrapt
python3-wsaccel
python3-wsgidav
python3-wsproto
python3-wtforms
python3-wxgtk4.0
python3-xattr
python3-xcffib
python3-xdg
python3-xlib
python3-xlrd
python3-xlsxwriter
python3-xlutils
python3-xlwt
python3-xmltodict
python3-yaml
python3-yara
python3-yarl
python3-yaswfp
python3-yattag
python3-zapv2
python3-zc.lockfile
python3-zict
python3-zipp
python3-zlib-wrapper
python3-zmq
python3-zombie-imp
python3-zombie-telnetlib
python3-zope.deprecation
python3-zope.event
python3-zope.interface
python3-zopfli
python3-zstandard
python3-zstd
python3.13
python3.13-dev
python3.13-minimal
python3.13-tk
python3.13-venv
qemu-block-extra
qemu-guest-agent
qemu-system-common
qemu-system-data
qemu-system-gui
qemu-system-modules-opengl
qemu-system-modules-spice
qemu-system-x86
qemu-user
qemu-user-binfmt
qemu-utils
qrencode
qsslcaudit
qt5-gtk-platformtheme:amd64
qt5ct
qt6-base-dev-tools
qt6-gtk-platformtheme:amd64
qt6-qpa-plugins:amd64
qt6-svg-plugins:amd64
qt6-translations-l10n
qt6-wayland:amd64
qt6ct
qtbase5-dev-tools
qtchooser
qterminal
qterminal-l10n
qtermwidget-data
qttranslations5-l10n
qtwayland5:amd64
quark-engine
racc
radare2
radiotap-library:amd64
rainbowcrack
rake
rarcrack
raven
rcracki-mt
rcs
rdesktop
read-edid
readline-common
readpe
reaver
rebind
recode
recon-ng
reconspider
recordmydesktop
recoverdm
recoverjpeg
redeye
redfang
redis-server
redis-tools
redsnarf
redsocks
reglookup
reglookup-doc
regripper
rephrase
responder
rev-proxy-grapher
rfcat
rfdump
rfkill
ridenum
rifiuti
rifiuti2
ristretto
rizin
rizin-cutter
rkhunter
rling
rlwrap
robotstxt
ropper
routerkeygenpc
routersploit
rpcbind
rpcsvc-proto
rpm
rpm-common
rpm2cpio
rsakeyfind
rsh-redone-client
rsmangler
rsync
rsyslog
rtkit
rtl-sdr
rtpbreak
rtpflood
rtpinsertsound
rtpmixsound
rubeus
ruby
ruby-activesupport
ruby-addressable
ruby-async
ruby-async-dns
ruby-async-http
ruby-async-io
ruby-async-pool
ruby-atomic:amd64
ruby-awesome-print
ruby-base64
ruby-buftok
ruby-builder
ruby-bundler
ruby-childprocess
ruby-cms-scanner
ruby-coderay
ruby-colorize
ruby-concurrent
ruby-connection-pool
ruby-console
ruby-csv
ruby-dev:amd64
ruby-did-you-mean
ruby-domain-name
ruby-ecdsa
ruby-equalizer
ruby-erubi
ruby-ethon
ruby-ffi:amd64
ruby-ffi-compiler
ruby-fiber-local
ruby-fxruby
ruby-get-process-mem
ruby-glu
ruby-gssapi
ruby-gyoku
ruby-hitimes:amd64
ruby-http
ruby-http-cookie
ruby-http-form-data
ruby-http-parser
ruby-http-parser.rb
ruby-httpclient
ruby-i18n
ruby-iostruct
ruby-ipaddress
ruby-json:amd64
ruby-jwt
ruby-levenshtein
ruby-libv8-node
ruby-little-plugger
ruby-logging
ruby-mechanize
ruby-memoizable
ruby-method-source
ruby-mime
ruby-mime-types
ruby-mime-types-data
ruby-mini-exiftool
ruby-mini-portile2
ruby-mini-racer
ruby-minitest
ruby-multi-json
ruby-multipart-post
ruby-naught
ruby-net-http-digest-auth
ruby-net-http-persistent
ruby-net-http-pipeline
ruby-net-telnet
ruby-nfnetlink
ruby-nfqueue
ruby-nio4r
ruby-nokogiri
ruby-nori
ruby-ntlm
ruby-oj:amd64
ruby-opengl
ruby-opt-parse-validator
ruby-pedump
ruby-pkg-config
ruby-progressbar
ruby-protocol-hpack
ruby-protocol-http
ruby-protocol-http1
ruby-protocol-http2
ruby-public-suffix
ruby-rainbow
ruby-rchardet
ruby-ruby2-keywords
ruby-rubygems
ruby-salsa20
ruby-sdbm:amd64
ruby-selenium-webdriver
ruby-sha3
ruby-simple-oauth
ruby-snmp
ruby-spider
ruby-sqlite3
ruby-thread-safe
ruby-timers
ruby-traces
ruby-trollop
ruby-twitter
ruby-typhoeus
ruby-tzinfo
ruby-unf
ruby-unf-ext
ruby-webrick
ruby-webrobots
ruby-websocket
ruby-winrm
ruby-winrm-fs
ruby-xmlrpc
ruby-yajl
ruby-zhexdump
ruby-zip
ruby3.3
ruby3.3-dev:amd64
ruby3.3-doc
rubygems-integration
runc
runit-helper
rz-ghidra
s3scanner
safecopy
sakis3g
samba
samba-ad-dc
samba-ad-provision
samba-common
samba-common-bin
samba-dsdb-modules:amd64
samba-libs:amd64
samdump2
sane-airscan
sane-utils
sara
sasquatch
sbd
scalpel
screen
scrounge-ntfs
sctpscan
seabios
seclists
secure-socket-funneling-windows-binaries
sed
selinux-utils
sendemail
sensible-utils
sentrypeer
set
sfuzz
sgml-base
sgml-data
shared-mime-info
sharphound
sharpshooter
shed
shellfire
shellnoob
shellter
sherlock
sickle-tool
sidguesser
siege
sigma-cli
silenttrinity
siparmyknife
sipcrack
sipp
sippts
sipsak
sipvicious
skipfish
sleuthkit
slimtoolkit
sliver
slowhttptest
smartmontools
smbclient
smbmap
smtp-user-enum
sn0int
sniffjoke
snmp
snmpcheck
snmpd
snmpenum
snort
snort-common
snort-common-libraries
snort-rules-default
snowdrop
soapyosmo-common0.8:amd64
soapysdr-tools
soapysdr0.8-module-airspy:amd64
soapysdr0.8-module-all:amd64
soapysdr0.8-module-audio:amd64
soapysdr0.8-module-bladerf:amd64
soapysdr0.8-module-hackrf:amd64
soapysdr0.8-module-lms7:amd64
soapysdr0.8-module-mirisdr:amd64
soapysdr0.8-module-osmosdr:amd64
soapysdr0.8-module-redpitaya:amd64
soapysdr0.8-module-remote:amd64
soapysdr0.8-module-rfspace:amd64
soapysdr0.8-module-rtlsdr:amd64
soapysdr0.8-module-uhd:amd64
socat
sonnet6-plugins:amd64
sound-icons
sound-theme-freedesktop
sox
sparrow-wifi
sparta-scripts
spectools
speech-dispatcher
speech-dispatcher-audio-plugins:amd64
speech-dispatcher-espeak-ng
sphinx-common
sphinx-rtd-theme-common
spiderfoot
spike
spire
split-select
sploitscan
spooftooph
spray
sprayhound
sprayingtoolkit
spraykatz
sqldict
sqlite3
sqlitebrowser
sqlmap
sqlmc
sqlninja
sqlsus
sqsh
squashfs-tools
sqv
ssdeep
sse3-support
sse4.2-support
sshuttle
ssl-cert
ssldump
sslh
sslscan
sslsniff
sslsplit
sslstrip
sslyze
starkiller
statsprocessor
stegcracker
steghide
stegosuite
stegsnow
strongswan-charon
strongswan-libcharon
strongswan-starter
stunnel4
subfinder
subjack
sublist3r
subversion
sucrack
sudo
suricata
suricata-update
swaks
syft
sysstat
system-config-printer
system-config-printer-common
system-config-printer-udev
system-tools-backends
systemd
systemd-sysv
systemd-timesyncd
sysvinit-utils
t1utils
t50
tango-icon-theme
tar
tasksel
tasksel-data
taskwarrior
tcl
tcl-expect:amd64
tcl8.6
tcpdump
tcpflow
tcpick
tcpreplay
tdb-tools
teamsploit
terminator
termineter
terraform
testdisk
testng
testssl.sh
tetragon
tex-common
tex-gyre
texlive-base
texlive-binaries
texlive-fonts-recommended
texlive-latex-base
texlive-latex-extra
texlive-latex-recommended
texlive-pictures
texlive-plain-generic
tftp-hpa
tftpd32
thc-ipv6
thc-pptp-bruter
thc-ssl-dos
theharvester
thehive
thunar
thunar-archive-plugin:amd64
thunar-data
thunar-gtkhash
thunar-volman
tiger
tightvncpasswd
tightvncserver
timgm6mb-soundfont
tini
tinja
tipa
tk
tk8.6
tk8.6-blt2.5
tlssled
tmux
tnftp
tnscmd10g
toilet-fonts
tpm-udev
traceroute
tree
tripwire
trivy
truecrack
trufflehog
tshark
tumbler
tumbler-common
tundeep
twofi
tzdata
tzdata-legacy
ubertooth
ubertooth-firmware
ucf
udev
udisks2
udptunnel
uhd-host
uhd-images
unar
unblob
undbx
unhide
unhide.rb
unicode-data
unicorn-magic
unicornscan
uniscan
unix-privesc-check
unixodbc-common
unrar
unzip
update-inetd
upower
upx-ucl
urlcrazy
urlscan
usb-modeswitch
usb-modeswitch-data
usb.ids
usbmuxd
usbutils
util-linux
uuid-dev:amd64
uuid-runtime
uwsgi-core
uwsgi-plugin-python3
va-driver-all:amd64
vboot-kernel-utils
vboot-utils
vdpau-driver-all:amd64
veil
villain
vim
vim-common
vim-gtk3
vim-gui-common
vim-runtime
vim-tiny
vinetto
vlan
voiphopper
vopono
vpnc
vpnc-scripts
wafw00f
wamerican
wapiti
watobo
waybackpy
wce
weasyprint
web-cache-vulnerability-scanner
webacoo
webscarab
webshells
websploit
weevely
wfuzz
wget
wgetpaste
whatmask
whatweb
whiptail
whois
wifi-honey
wifiphisher
wifipumpkin3
wifite
wig
wig-ng
winbind
windows-binaries
windows-privesc-check
wine
wine64
winregfs
wireguard-tools
wireless-regdb
wireless-tools
wireplumber
wireshark
wireshark-common
witnessme
wixl
wixl-data
wmi-client
wordlistraider
wordlists
wotmate
wpa-sycophant
wpasupplicant
wpscan
wxpython-tools
x11-apps
x11-common
x11-session-utils
x11-utils
x11-xkb-utils
x11-xserver-utils
x11proto-dev
xar
xauth
xbitmaps
xbrlapi
xcape
xclip
xcvt
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-user-dirs
xdg-user-dirs-gtk
xdg-utils
xdotool
xfce4
xfce4-appfinder
xfce4-battery-plugin:amd64
xfce4-clipman
xfce4-clipman-plugin
xfce4-cpufreq-plugin:amd64
xfce4-cpugraph-plugin:amd64
xfce4-datetime-plugin:amd64
xfce4-diskperf-plugin:amd64
xfce4-fsguard-plugin:amd64
xfce4-genmon-plugin:amd64
xfce4-helpers
xfce4-netload-plugin:amd64
xfce4-notifyd
xfce4-panel
xfce4-panel-profiles
xfce4-places-plugin:amd64
xfce4-power-manager
xfce4-power-manager-data
xfce4-power-manager-plugins
xfce4-pulseaudio-plugin:amd64
xfce4-screensaver
xfce4-screenshooter
xfce4-sensors-plugin
xfce4-session
xfce4-settings
xfce4-systemload-plugin:amd64
xfce4-taskmanager
xfce4-timer-plugin:amd64
xfce4-verve-plugin:amd64
xfce4-wavelan-plugin:amd64
xfce4-whiskermenu-plugin
xfce4-xkb-plugin:amd64
xfconf
xfdesktop4
xfdesktop4-data
xfonts-100dpi
xfonts-75dpi
xfonts-base
xfonts-encodings
xfonts-scalable
xfonts-utils
xfwm4
xiccd
xinit
xkb-data
xkbset
xml-core
xml-twig-tools
xmount
xorg
xorg-docs-core
xorg-sgml-doctools
xplico
xserver-common
xserver-xephyr
xserver-xorg
xserver-xorg-core
xserver-xorg-input-all
xserver-xorg-input-libinput
xserver-xorg-input-wacom
xserver-xorg-legacy
xserver-xorg-video-all
xserver-xorg-video-amdgpu
xserver-xorg-video-ati
xserver-xorg-video-fbdev
xserver-xorg-video-intel
xserver-xorg-video-nouveau
xserver-xorg-video-qxl
xserver-xorg-video-radeon
xserver-xorg-video-vesa
xserver-xorg-video-vmware
xsltproc
xspy
xsrfprobe
xsser
xterm
xtightvncviewer
xtrans-dev
xtrx-dkms
xvfb
xxd
xz-utils
yara
yelp
yelp-xsl
yersinia
zaproxy
zenmap
zerofree
zim
zip
zipalign
zipcmp
zipmerge
ziptool
zlib1g:amd64
zlib1g-dev:amd64
zonedb
zsh
zsh-autosuggestions
zsh-common
zsh-syntax-highlighting
zstd
